<a href="https://colab.research.google.com/github/yun-aha/GSTEC/blob/main/210622.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>concatenate 부터</h1>

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6]])
arr12=np.concatenate((arr1,arr2),axis=0)
print(arr12)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr3=np.array([[3,4,0,2,1]]) #(1,5)
arr4=np.array([[0]])     #(1,1)
arr34=np.concatenate((arr3,arr4),axis=1)
print(arr34)
print('----------------')
arr5=np.array([[0,5,3],[2,4,1]])
arr6=np.array([[0],[1]])
arr56=np.concatenate((arr5,arr6),axis=1)
print(arr56)

[[3 4 0 2 1 0]]
----------------
[[0 5 3 0]
 [2 4 1 1]]


In [ ]:
arr5=np.array([[2,5],[3,0],[1,7],[6,4]])   #(4,2)
arr6=np.array([[1,2],[3,4],[0,5]])         #(3,2)
arr56=np.concatenate((arr5,arr6),axis=0)
print(arr56)
print('-=-==-=-=-=-=-===============-=-')
arr7=np.array([[[19,17,10,8,3],[5,12,9,0,1]],[[11,6,16,15,14],[4,2,13,18,7]]])  #(2,2,5)
arr8=np.array([[[13,1,7,3],[15,5,2,14]],[[4,12,11,10],[8,6,9,0]]])              #(2,2,4)
arr78=np.concatenate((arr7,arr8),axis=2)
print(arr78)

[[2 5]
 [3 0]
 [1 7]
 [6 4]
 [1 2]
 [3 4]
 [0 5]]
-=-==-=-=-=-=-===============-=-
[[[19 17 10  8  3 13  1  7  3]
  [ 5 12  9  0  1 15  5  2 14]]

 [[11  6 16 15 14  4 12 11 10]
  [ 4  2 13 18  7  8  6  9  0]]]


In [ ]:
arr9=np.zeros((3,5,4))
arr10=np.ones((1,5,4))
arr90=np.concatenate((arr9,arr10),axis=0)
print(arr90)
print('==========================')
arr11=np.zeros((3,5,4))
arr12=np.ones((3,2,4))
arr121=np.concatenate((arr11,arr12),axis=1)
print(arr121)
print('++++++++++++++++++++++++++')
arr13=np.zeros((3,5,4))
arr14=np.ones((3,5,1))
arr134=np.concatenate((arr13,arr14),axis=2)
print(arr134)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
++++++++++++++++++++++++++
[[[0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]]

 [[0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1.]]]


In [ ]:
from PIL import Image
img=np.asarray(Image.open('lena.png'))
img=img.copy()
img2=img.copy()
img=np.concatenate((img,img2),1)
img=Image.fromarray(img,'RGB')
img.save('out.png')


<h1>원소 제거 : np.delete()</h1>

In [ ]:
arr15=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr16=np.delete(arr15,1,1)
print(arr16)
print('------------------')
arr17=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr18=np.delete(arr17,(1,3,5),None)
print(arr18)
print('====================')
arr19=np.array([[[1,4,20],[13,8,24]],[[19,15,11],[6,16,7]]])
arr20=np.delete(arr19,(0,1),2)
print(arr20)

[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]
------------------
[ 1  3  5  7  8  9 10 11 12]
[[[20]
  [24]]

 [[11]
  [ 7]]]


In [ ]:
arr21=np.array([[[1,4,20,23,28],[13,8,24,21,5]],[[25,29,26,18,2],[14,27,9,10,3]],[[19,15,11,22,0],[6,16,7,17,12]]])
arr22=np.delete(arr21,0)
arr23=np.delete(arr21,(2,4,7))
arr24=np.delete(arr21,1,0)
arr25=np.delete(arr21,(0,1),2)
print(arr22)
print(arr23)
print('--------------')
print(arr24)
print('------------')
print(arr25)

[ 4 20 23 28 13  8 24 21  5 25 29 26 18  2 14 27  9 10  3 19 15 11 22  0
  6 16  7 17 12]
[ 1  4 23 13  8 21  5 25 29 26 18  2 14 27  9 10  3 19 15 11 22  0  6 16
  7 17 12]
--------------
[[[ 1  4 20 23 28]
  [13  8 24 21  5]]

 [[19 15 11 22  0]
  [ 6 16  7 17 12]]]
------------
[[[20 23 28]
  [24 21  5]]

 [[26 18  2]
  [ 9 10  3]]

 [[11 22  0]
  [ 7 17 12]]]


In [ ]:
from PIL import Image
img=np.asarray(Image.open('lena.png'))
img=img.copy()
img=np.delete(img,np.s_[100:300],1)
img=Image.fromarray(img,'RGB')
img.save('out2.png')

<h1>reshape, size, ndim, arange</h1>

In [ ]:
arr26=np.arange(0,40)
arr_6=np.reshape(arr26,(5,-1))   #-1을 쓰면 원래 배열의 길이와 남은 차원에서 유추하여 자동으로 형태 변경
print('-1을 쓰면',arr_6)
arr26=np.reshape(arr26,(4,2,5))
print('ndim : ',arr26.ndim)
print('size :',arr26.size)
print('shape :',arr26.shape)
print(arr26)
print('-----------------')
arr27=np.arange(6)
arr27=arr27.reshape(3,2)
print(arr27)

-1을 쓰면 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]
ndim :  3
size : 40
shape : (4, 2, 5)
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]]
-----------------
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
arr28=np.arange(0,40)
arr29=np.reshape(arr28,(2,20))
print(arr29)
arr30=np.reshape(arr28,(1,5,8))
print(arr30)
arr31=np.reshape(arr28,(4,2,5))
print(arr31)
arr32=np.reshape(arr28,(5,8))
print(arr32)
print('----------------------------------------')
arr33=np.arange(0,72)
arr34=np.reshape(arr33,(6,2,6))
print(arr34)
arr35=np.reshape(arr33,(8,9))
print(arr35)
print('--------resize')
arr36=np.resize(arr35,(3,3,8))
print(arr36)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]]
[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30 31]
  [32 33 34 35 36 37 38 39]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]]
----------------------------------------
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[36 37 38 39 40 41]
  [42 43 44 45 46 47]]

 [[48 49 50 51 52 53]
  [54 55 56 57 58 59]]

 [[60 61 62 63 64 65]
  [66 67 68 69 70 71]]]
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35

In [ ]:
from PIL import Image
img=np.asarray(Image.open('lena.png'))
print(img.ndim)
print(img.size)
print(img.shape)
img=img.reshape(256,1024,3)
img=Image.fromarray(img,'RGB')
img.save('out3.png')

3
786432
(512, 512, 3)


<h2>인덱싱 및 슬라이싱</h2>

In [ ]:
arr37=np.arange(20).reshape(4,5)
print(arr37)
print(arr37[1,3])
print(arr37[0])
print(arr37[0:1,1])
print('------------')
print(arr37[0:2,1:3])
print('===============')
arr38=np.arange(42).reshape(6,7)
print(arr38[2,3])
print(arr38[3,6])
print(arr38[5,0])
print(arr38[0,1])
print(arr38[:,3])
print(arr38[1,:])
print(arr38[4,:])
print(arr38[:,6])
print('------------------------------')
print(arr38[:,1:4])
print(arr38[1:3,:])
print(arr38[2:5,:])
print(arr38[:,5:7])
print(arr38[arr38<5])
print(arr38[arr38>=10])
print(arr38[4:6,3:5])
print(arr38[1:4,2:5])
print(arr38[1:6,5:7])
print(arr38[1:4,0:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
8
[0 1 2 3 4]
[1]
------------
[[1 2]
 [6 7]]
17
27
35
1
[ 3 10 17 24 31 38]
[ 7  8  9 10 11 12 13]
[28 29 30 31 32 33 34]
[ 6 13 20 27 34 41]
------------------------------
[[ 1  2  3]
 [ 8  9 10]
 [15 16 17]
 [22 23 24]
 [29 30 31]
 [36 37 38]]
[[ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
[[14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[ 5  6]
 [12 13]
 [19 20]
 [26 27]
 [33 34]
 [40 41]]
[0 1 2 3 4]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41]
[[31 32]
 [38 39]]
[[ 9 10 11]
 [16 17 18]
 [23 24 25]]
[[12 13]
 [19 20]
 [26 27]
 [33 34]
 [40 41]]
[[ 7  8  9]
 [14 15 16]
 [21 22 23]]


In [ ]:
arr39=np.arange(0,50).reshape(2,5,5)
print(arr39[0,2,:])
print(arr39[1,:,4])
print(arr39[1,0:3,:])
print(arr39[0,:,2:4])
print(arr39[:,0:2,2:4])
print(arr39[:,2:5,1:4])

[10 11 12 13 14]
[29 34 39 44 49]
[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
[[ 2  3]
 [ 7  8]
 [12 13]
 [17 18]
 [22 23]]
[[[ 2  3]
  [ 7  8]]

 [[27 28]
  [32 33]]]
[[[11 12 13]
  [16 17 18]
  [21 22 23]]

 [[36 37 38]
  [41 42 43]
  [46 47 48]]]


In [ ]:
from PIL import Image
img=np.asarray(Image.open('lena.png'))
img=img.copy()
img2=img.copy()
img=img[100:400,100:400,:]
img=Image.fromarray(img,'RGB')
img.save('out4.png')

img2=img2[300:100:-1,500:250:-1,:]
img2=Image.fromarray(img2,'RGB')
img2.save('out5.png')

In [ ]:
arr40=np.arange(1,13).reshape(1,3,4)
print(arr40[arr40<5])
print(arr40[arr40>=5])
print(arr40[arr40>2] & arr40[arr40<11])
print(arr40)
arr40[arr40<5]=3
print(arr40)
arr41=np.arange(1,11).reshape(2,5)
arr41[arr41<5]=0
print(arr41)


[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
[1 0 1 4 5 0 1 8 9 8]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
[[[ 3  3  3  3]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
[[ 0  0  0  0  5]
 [ 6  7  8  9 10]]


In [ ]:
from PIL import Image
img=np.asarray(Image.open('lena.png'))
img=img.copy()
img2=img.copy()
img[img<=100]=0
img=Image.fromarray(img,'RGB')
img.save('out_condition.png')

img2[img2>=150]=255
img2=Image.fromarray(img2,'RGB')
img2.save('out_condition2.png')

<h1>배열의 차원 확장 newaxis, expand_dims</h1>

In [ ]:
arr42=np.arange(1,21).reshape(5,4)
arr43=arr42[np.newaxis,:]
print(arr43.shape)
print(arr43)
arr44=arr42[:,np.newaxis]
print(arr44.shape)
print(arr44)

(1, 5, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]
  [17 18 19 20]]]
(5, 1, 4)
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]

 [[13 14 15 16]]

 [[17 18 19 20]]]


In [ ]:
arr45=np.arange(0,20).reshape(4,5)
arr45=arr45[:,np.newaxis]
print(arr45.shape)
print(arr45)
print('---------------------------------------')

arr46=np.arange(10,40).reshape(5,6)

arr47=arr46[:,:,np.newaxis]
print(arr47.shape)
print(arr47)
print('----')
arr46=arr46[np.newaxis,:]
print(arr46.shape)
print(arr46)


(4, 1, 5)
[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]

 [[15 16 17 18 19]]]
---------------------------------------
(5, 6, 1)
[[[10]
  [11]
  [12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]
  [20]
  [21]]

 [[22]
  [23]
  [24]
  [25]
  [26]
  [27]]

 [[28]
  [29]
  [30]
  [31]
  [32]
  [33]]

 [[34]
  [35]
  [36]
  [37]
  [38]
  [39]]]
----
(1, 5, 6)
[[[10 11 12 13 14 15]
  [16 17 18 19 20 21]
  [22 23 24 25 26 27]
  [28 29 30 31 32 33]
  [34 35 36 37 38 39]]]


In [ ]:
arr47=np.arange(0,30).reshape(5,6)
arr48=arr47[:,np.newaxis,:]
print(arr48)
print(arr48.shape)
arr47=np.expand_dims(arr47,axis=(0,1,2,5))
print(arr47)
print(arr47.shape)

[[[ 0  1  2  3  4  5]]

 [[ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]]

 [[18 19 20 21 22 23]]

 [[24 25 26 27 28 29]]]
(5, 1, 6)
[[[[[[ 0]
     [ 1]
     [ 2]
     [ 3]
     [ 4]
     [ 5]]

    [[ 6]
     [ 7]
     [ 8]
     [ 9]
     [10]
     [11]]

    [[12]
     [13]
     [14]
     [15]
     [16]
     [17]]

    [[18]
     [19]
     [20]
     [21]
     [22]
     [23]]

    [[24]
     [25]
     [26]
     [27]
     [28]
     [29]]]]]]
(1, 1, 1, 5, 6, 1)


In [ ]:
arr48=np.arange(3)
print(arr48)
arr49=arr48[:,np.newaxis]
print(arr49)
arr50=arr48[:,np.newaxis]*arr48
print(arr50)
arr51=arr48[:,np.newaxis]+arr48
print(arr51)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 0 0]
 [0 1 2]
 [0 2 4]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


<h1>part8 기존 데이터에서 배열 만들기</h1>

In [ ]:
arr1=np.array([[1,1,],[2,2]])
arr2=np.array([[3,3],[4,4]])
arr11=np.vstack((arr1,arr2))
print(arr11)
arr12=np.hstack((arr1,arr2))
print(arr12)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


In [ ]:
arr=np.arange(1,25).reshape(6,4)
print(arr)
arr1,arr2,arr3=np.vsplit(arr,3)
print('---------')
print(arr1)
print('---------')
print(arr2)
print('---------')
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
---------
[[1 2 3 4]
 [5 6 7 8]]
---------
[[ 9 10 11 12]
 [13 14 15 16]]
---------
[[17 18 19 20]
 [21 22 23 24]]


In [ ]:
arr10=np.arange(1,25).reshape(2,12)
arr11,arr20,arr30=np.hsplit(arr10,3)
print(arr11)
print('---------')
print(arr20)
print('---')
print(arr30)

[[ 1  2  3  4]
 [13 14 15 16]]
---------
[[ 5  6  7  8]
 [17 18 19 20]]
---
[[ 9 10 11 12]
 [21 22 23 24]]


복제

In [ ]:
arr1=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
arr2=arr1
print(arr2 is arr1)
print(id(arr1))
print(id(arr2))

True
139984969941920
139984969941920


In [ ]:
arr1=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
arr2=arr1.view()
print(arr1 is arr2)
arr1[0]=999
print(arr2)
print(id(arr1))
print(id(arr2))

False
[[999 999 999 999]
 [  4   5   6   7]
 [  8   9  10  11]]
139984969848512
139984969850672


In [ ]:
arr1=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
arr2=arr1.copy()
print(arr1 is arr2)
arr1[0][2]=99
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))

False
[[ 0  1 99  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
139984970307504
139984969922080


<h1>9.배열연산</h1>

In [ ]:
arr1=np.array([1,2])
arr2=np.ones(2,dtype=int)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
arr3=np.array([1,2,3,4])
print(arr3.sum())
arr4=np.array([[1,1],[2,2]])
print(arr4.sum(axis=0))
print(arr4.sum(axis=1))

[2 3]
[0 1]
[1 2]
[1. 2.]
10
[3 3]
[2 4]


In [ ]:
arr=np.array([[4,2,5,7,2,7],[9,54,3,8,4,67],[14,36,58,547,32,7]])
print(arr.max(axis=0))
print(arr.max(axis=1))
print(arr.max())   #axis=None
print('-----------')
print(arr.min(axis=0))
print(arr.min(axis=1))
print(arr.min())
print('=======================')
print(arr.mean(axis=0))
print(arr.mean(axis=1))
print(arr.mean())
print('-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=')
print(arr.std(axis=0))
print(arr.std(axis=1))
print(arr.std())

[ 14  54  58 547  32  67]
[  7  67 547]
547
-----------
[4 2 3 7 2 7]
[2 3 7]
2
[  9.          30.66666667  22.         187.33333333  12.66666667
  27.        ]
[  4.5         24.16666667 115.66666667]
48.111111111111114
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[  4.0824829   21.56128217  25.46893533 254.32306663  13.69509239
  28.28427125]
[  2.06155281  26.04749935 193.59120733]
122.74539542795661


In [ ]:
arr=np.array([[4,2,5,7,2,7],[9,54,3,8,4,67],[14,36,58,547,32,7]])
print(arr.prod(axis=0))
print(arr.prod(axis=1))
print(arr.prod())
print('--------------------')
arr1=np.eye(2)
print(arr1)
arr2=np.ones((2,2))*2
print(arr2)
print('')
print(arr1.dot(arr2))   #내적..?을 구해줌
print(arr1.dot(arr2).dot(arr2))
print('===============================================')
arr1=np.array([[1,0],[0,1]])
arr2=np.array([[4,1],[2,2]])
print(np.matmul(arr1,arr2))

[  504  3888   870 30632   256  3283]
[      3920    3125952 3581738496]
6996174903569809408
--------------------
[[1. 0.]
 [0. 1.]]
[[2. 2.]
 [2. 2.]]

[[2. 2.]
 [2. 2.]]
[[8. 8.]
 [8. 8.]]
[[4 1]
 [2 2]]


<h1>10. 브로드캐스트 </h1>


In [ ]:
arr=np.array([1.0,2.0])
print(arr*1.6)

[1.6 3.2]


In [ ]:
arr=np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
arr1=np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])
print(arr+arr1)
arr2=np.array([0,1,2])
print(arr+arr2)
print('-------------------')
arr3=np.array([[0],[11],[22],[35]])
arr4=np.array([0,1,4])
print(arr3+arr4)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
-------------------
[[ 0  1  4]
 [11 12 15]
 [22 23 26]
 [35 36 39]]


<h1>11. 난수 생성</h1>

In [ ]:
print(np.random.randint(2,10))
print(np.random.randint(2,10,size=10))
print(np.random.randint(5,size=(2,4)))
print(np.random.rand(3,2))
print(np.random.randn(2,4))

4
[4 8 7 6 9 3 9 3 7 5]
[[4 3 1 4]
 [1 0 4 4]]
[[0.42626892 0.63887295]
 [0.08779568 0.39195278]
 [0.11172806 0.2513231 ]]
[[ 0.30216301 -0.3984355  -0.15807776  1.4493551 ]
 [-0.20064485 -0.18929798 -0.02071596 -1.14519885]]


In [ ]:
arr=np.arange(10)
np.random.shuffle(arr)
print(arr)
arr1=np.arange(9).reshape((3,3))
np.random.shuffle(arr1)      #다차원 배열의 첫번째 축을 따른 배열만 섞인다.
print(arr1)

print(np.random.choice(5,3,p=[0.1,0,0.3,0.6,0])) 
#p는 각 항목과 관련된 확률,선택사항,지정되지 않은 경우 모든 항목에 대해 균일한 분포 가정


[4 6 3 5 9 0 2 7 8 1]
[[6 7 8]
 [3 4 5]
 [0 1 2]]
[3 2 3]


<h1>12. 고유 항목 및 개수를 얻는 방법</h1>

In [ ]:
arr=np.array([11,21,11,12,13,14,15,11,14,18,19,20,21,20,22,23,24,25,224,22])
arr1=np.unique(arr)
print(arr1)
arr1,arr2=np.unique(arr,return_counts=True)    #return_counts : True인 경우 각 고유 값이 나타나는 횟수 반환
print(arr2)

[ 11  12  13  14  15  18  19  20  21  22  23  24  25 224]
[3 1 1 2 1 1 1 2 2 2 1 1 1 1]


In [ ]:
arr_2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4]])
arr_u=np.unique(arr_2,axis=1) #axis=0은 고유한 행, axis=1은 고유한 열
print(arr_u)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


<h1>13. 행렬전치 및 재구성</h1>

In [ ]:
arr=np.arange(4).reshape((2,2))
print(arr)
print(np.transpose(arr))

print('-----------')

arr1=np.ones((1,2,3))
print(arr1)
print('============')
print(np.transpose(arr1,(1,0,2)).shape)        #???

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]
-----------
[[[1. 1. 1.]
  [1. 1. 1.]]]
(2, 1, 3)


In [ ]:
arr=np.array([[1.,2.],[3.,4.]])
print(arr)
print(arr.T)
arr1=np.array([[1.,2.,3.,4.]])
print(arr1)
print(arr1.T)

[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]
[[1. 2. 3. 4.]]
[[1.]
 [2.]
 [3.]
 [4.]]
