<a href="https://colab.research.google.com/github/yun-aha/GSTEC/blob/main/210630.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. 딥러닝 & 강화학습

In [ ]:
#MSE
#1
y_1 = 21
y_2 = 10
y_3 = 14
y_hat_1 = 15
y_hat_2 = 12
y_hat_3 = 18

a = (y_1 - y_hat_1)**2
b = (y_2 - y_hat_2)**2
c = (y_3 - y_hat_3)**2
print(a, b, c)

import numpy as np
n = 3
mse = (a+b+c)/n

print("MSE : {}".format(np.round(mse,4)))

36 4 16
MSE : 18.6667


In [ ]:
#MSE
#2
import numpy as np
y=[21,10,14]
yh=[15,12,18]
AI=(y[0]-yh[0])**2+(y[1]-yh[1])**2+(y[2]-yh[2])**2
n=3
mse=AI/n
print(np.round(mse,4))

18.6667


성별 m,f,i를 0,1,2로 변경하면 선형적 문제!  
--> 원핫벡터 One-hot Vector  


In [ ]:
#1
rows=['M',0.455,0.365,0.0950] # -> [1,0,0,0.455,0.365,0.0950]
if rows[0]=='M':
  m=[1,0,0]
  rows.pop(0)
  rows=m+rows
elif rows[0]=='F':
  f=[0,1,0]
  rows.pop(0)
  rows=f+rows
else:
  i=[0,0,1]
  rows=i+rows
print(rows)

[1, 0, 0, 0.455, 0.365, 0.095]


In [ ]:
#2 np.zeros 사용
rows = ['I', 0.455, 0.365, 0.095] # ---->> [1, 0, 0, 0.455, 0.365, 0.095]
data = np.zeros(6)
print(data)
if rows[0] == 'M':
    data[0] = 1
elif rows[0] == 'F':
    data[1] = 1
elif rows[0] == 'I':
    data[2] = 1

print('----------------------')
print(data)
print(rows)
print("=========================")
print(data)

data[3:] = rows[1:]
print(data)

[0. 0. 0. 0. 0. 0.]
----------------------
[0. 0. 1. 0. 0. 0.]
['I', 0.455, 0.365, 0.095]
[0. 0. 1. 0. 0. 0.]
[0.    0.    1.    0.455 0.365 0.095]


In [ ]:
import csv
with open('./abalone_mini.csv') as csvfile:
  csvreader=csv.reader(csvfile)
  
  rows=[]
  for row in csvreader:
    rows.append(row)
print(rows)

[['M', '0.455', '0.365', '0.095', '0.514', '0.2245', '0.101', '0.15', '15'], ['M', '0.35', '0.265', '0.09', '0.2255', '0.0995', '0.0485', '0.07', '7'], ['F', '0.53', '0.42', '0.135', '0.677', '0.2565', '0.1415', '0.21', '9'], ['M', '0.44', '0.365', '0.125', '0.516', '0.2155', '0.114', '0.155', '10'], ['I', '0.33', '0.255', '0.08', '0.205', '0.0895', '0.0395', '0.055', '7']]


In [ ]:
#1
m=[1,0,0]
f=[0,1,0]
i=[0,0,1]
rows_s=[]
for r in rows:
  if r[0]=='M':
    r.pop(0)
    r=m+r
    rows_s.append(r)
  elif r[1]=='F':
    r.pop(0)
    r=f+r
    rows_s.append(r)
  else:
    r.pop(0)
    r=i+r
    rows_s.append(r)
print(rows_s)

[[1, 0, 0, '0.455', '0.365', '0.095', '0.514', '0.2245', '0.101', '0.15', '15'], [1, 0, 0, '0.35', '0.265', '0.09', '0.2255', '0.0995', '0.0485', '0.07', '7'], [0, 0, 1, '0.53', '0.42', '0.135', '0.677', '0.2565', '0.1415', '0.21', '9'], [1, 0, 0, '0.44', '0.365', '0.125', '0.516', '0.2155', '0.114', '0.155', '10'], [0, 0, 1, '0.33', '0.255', '0.08', '0.205', '0.0895', '0.0395', '0.055', '7']]


In [ ]:
#2 
#enumerate함수 사용
data=np.zeros([5,11])
print(data)
for n,row in enumerate(rows):
  if row[0]=='M': data[n,0]=1
  elif row[0]=='F': data[n,1]=1
  elif row[0]=='I': data[n,2]=1
  data[n,3:]=row[1:]
print(data)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 1.      0.      0.      0.455   0.365   0.095   0.514   0.2245  0.101
   0.15   15.    ]
 [ 1.      0.      0.      0.35    0.265   0.09    0.2255  0.0995  0.0485
   0.07    7.    ]
 [ 0.      1.      0.      0.53    0.42    0.135   0.677   0.2565  0.1415
   0.21    9.    ]
 [ 1.      0.      0.      0.44    0.365   0.125   0.516   0.2155  0.114
   0.155  10.    ]
 [ 0.      0.      1.      0.33    0.255   0.08    0.205   0.0895  0.0395
   0.055   7.    ]]


In [ ]:
#함수에 함수 넣기
def main_exec():
  #import_data()
  model_init()
  #train_and_test()

RND_MEAN = 0
RND_STD = 1
def model_init():
  global weight, bias      #전역변수화
  weight = np.random.normal(RND_MEAN,RND_STD,size=1)
  bias = np.random.normal(RND_MEAN,RND_STD,size=1)

main_exec()
print('weight : ',weight)
print('bias : ',bias)

weight :  [1.53771869]
bias :  [-0.65914163]


#2. 머신러닝

In [ ]:
#토너먼트 9팀
#1
import random
t=[1,2,3,4,5,6,7,8,9]
a=[]
while len(t)>0:
  one=random.choice(t)
  t.remove(one)
  if len(t)==0:
    a.append(one)
    break
  two=random.choice(t)
  t.remove(two)
  a.append((one,two))
print(a)

print('===================================')
#2
teams=list(range(1,10))
random.shuffle(teams)
half=len(teams)//2
print(teams[:half], teams[half:])
print(teams)
print(list(zip(teams[:half],teams[half:])))

[(7, 5), (2, 4), (3, 8), (9, 1), 6]
[7, 6, 5, 3] [8, 1, 4, 9, 2]
[7, 6, 5, 3, 8, 1, 4, 9, 2]
[(7, 8), (6, 1), (5, 4), (3, 9)]


In [ ]:
#html 배포 -> https://app.netlify.com/teams/yun-aha/overview
#깃헙 연동
#web을 배포하면 default로 찾는 폴더 index.html

#3. 빅데이터 분석

In [ ]:
#특정 컬럼 가져오기
SELECT*FROM Country ORDER BY Code; 
SELECT Name, Code, Region, Population FROM Country ORDER BY Code;  
SELECT Name, Code, Region, Population FROM Country ORDER BY Population DESC;  #DESC는 내림차순
SELECT Name AS Country,Code FROM Country ORDER BY Code;   #컬럼을 불러와서 이름을 변경하여 출력할 수 있다.
SELECT Name AS Coutry,Population/1000 AS "Pop(1000s)"FROM Coutry; #간단한 수식을 적용할 수도 있다.

#SELECT + ORDER BY를 사용해서 정렬된 결과를 보여줄 수 있다.
SELECT Name FROM Country; #정렬x
SELECT Name FROM Country ORDER BY Name; #오름차순 정렬 default
SELECT Name FROM Country ORDER BY Name DESC; #내림차순 정렬
SELECT Name FROM Country ORDER BY NAme ASC;  #오름차순 정렬
SELECT Name,Continent FROM Country ORDER BY Continent,Naem; #두 개 이상의 컬럼으로 정렬
SELECT Name,Continent FROM Country ORDER BY Continent DESC, Name; #먼저 나오는 컬럼을 우선해서 정렬

#SELECT + WHERE를 사용해서 필터링 결과를 보여줄 수 있다.
#AND, OR 등으로 조건문을 연결할 수 있다.
#BETWEEN n1 AND n2 로 n1~n2로 레인지에 속하는 값만 필터링 할 수 있다.
SELECT Name, Continent, Population FROM Country WHERE Population <100000 ORDER BY Population DESC;
SELECT Name, Continent, Population FROM Country WHERE Population < 100000 AND Continent = 'Oceania' ORDER BY Population DESC;
SELECT Name, Population FROM Country WHERE Population BETWEEN 1000000 AND 10000000 ORDER BY Population DESC;
SELECT Name, Population FROM Country WHERE Population NOT BETWEEN 1000000 AND 10000000 ORDER BY Population DESC;

#SELECT + WHERE + LIKE을 사용해서 필터링 결과를 보여줄 수 있다.
#'%'는 불특정 문자열 부분을 의미하고 '_'는 불특정 문자를 의미한다.
SELECT Name,Continent FROM Country WHERE Name LIKE '%island';
SELECT Name,Continent FROM Country WHERE Name LIKE 'island%';
SELECT Name,Continent FROM Country WHERE Name LIKE '%island%';
SELECT Name,Continent FROM Country WHERE Name LIKE '_a%';   #두번째 문자가 'a'

#SELECT + WHERE + IN을 사용해서 멤버쉽 필터링 결과를 보여줄 수 있다.
SELECT Name,Continent FROM Country WHERE Continent IN ('Europe','Asia');
SELECT Name,Continent,Region FROM Country WHERE Region IN ('Western Europe','Eastern Europe') ORDER BY Region;
SELECT Name,Continent,Region FROM Country WHERE Region='Western Europe' OR Region='Eastern Europe' ORDER BY Region; 

#DISTINCT 키워드를 사용해서 중복을 제거하고 출력할 수 있다.
SELECT CountryCode, Name FROM City;
SELECT DISTINCT CountryCode FROM City;
SELECT COUNT(CountryCode)FROM City;
SELECT COUNT(DISTINCT CountryCode) FROM City;

#SELECT로 출력된 결과를 "가상"의 테이블로 사용하여 SELECT 문을 만들 수 있다. 
SELECT Name FROM (SELECT Code, Name, Continent FROM Country);
SELECT COUNT(*) FROM (SELECT DISTINCT CountryCode FROM City);


In [ ]:
#CREATE TABLE로 데이터 베이스에 테이블을 추가할 수 있다. 
CREATE TABLE test (a INT, b TEXT, c TEXT);   #'a','b','c'컬럼의 테이블 생성
CREATE TABLE IF NOT EXISTS test (a INT,b TEXT, c TEXT); #'a','b','c'컬럼의 테이블 중복 체크 후 생성
SELECT name FROM sqlite_master WHERE TYPE ='table'  #테이블 목록(SQLite)
PRAGMA table_info(test)  #특정 테이블에 대한 정보

#INSERT INTO ~ VALUES로 행을 추가할 수 있다.
INSERT INTO test VALUES (1, 'This','Right here!'); #1행 추가
INSERT INTO test (b,c) VALUES ('That','Over there!'); #'a'는 NULL , b와 c에 values추가
SELECT *FROM test;
#다른 테이블에서 SELECT로 가져온 결과로 행 추가 가능하다.
INSERT INTO test(a,b,c) SELECT id,name,description FROM item; #'item'테이블에서 가져온 결과를 test에 추가

#UPDATE + SET로 특정 행의 특정 컬럼 값을 변경할 수 있다.
UPDATE test SET c='Extra funny.' WHERE a=2;    #'c'컬럼의 값 변경
SELECT*FROM test;
UPDATE test SET c=NULL WHERE a=2;  #NULL값으로 변경
UPDATE test SET(b,c)=('T-Rex','Toy dinosaur')WHERE a=2;   #값 변경

#DELETE FROM으로 특정 행을 삭제할 수 있따.
DELETE FROM test WHERE a=2; #조건에 맞는 행 삭제
DELETE FROM test; #모든 행 삭제 , 테이블은 남음

#DROP TABLE로 특정 테이블을 삭제할 수 있다.
DROP TABLE test; #데이터베이스에서 'test'테이블 삭제
DROP TABLE IF EXISTS test; #존재여부 확인하고 데이터 베이스에서 'test'테이블 삭제

#NULL은 값이 아니라 결측치를 의미하여 0 또는 ''(공백)과는 다르다.
CREATE TABLE test (a INT, b TEXT, c TEXT);
INSERT INTO test(b,c) VALUES ('This','That');  #'a'에는 NULL을 넣어줌
SELECT *FROM test WHERE a=NULL; #작동 안함
SELECT*FROM test WHERE a IS NULL; #작동함
SELECT*FROM test WHERE a IS NOT NULL; #작동함
UPDATE test SET a=0 WHERE a IS NULL; #'a'컬럼의 NULL을 0값으로 채워 넣음.


괄호는 사용x
결측치 여부는 IS NULL


#4. 취업멘토링

* CB insights  
* classum  
* g3cloud  
* Crunchbase: Discover innovative companies and the people ...https://www.crunchbase.com

