<a href="https://colab.research.google.com/github/yun-aha/GSTEC/blob/main/210623.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>14. 배열을 뒤집는 방법<h1>

In [ ]:
import numpy as np
print('1차원 배열')
arr=np.array([1,2,3,4,5,6,7,8])
arr1=np.flip(arr)
print(arr1)
print('2차원 배열 뒤집기')
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr11=np.flip(arr)
print(arr11)
print('axis=0')
arr111=np.flip(arr,axis=0)
print(arr111)
print('axis=1')
arr1111=np.flip(arr,axis=1)
print(arr1111)

1차원 배열
[8 7 6 5 4 3 2 1]
2차원 배열 뒤집기
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
axis=0
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
axis=1
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


<h1>15. n차원 배열 재구성 및 flatten</h1>

In [ ]:
arr=np.array([[1,2],[3,4]])
print('c : ',arr.flatten(order='C'))
print('f : ',arr.flatten(order='F'))
print('a : ',arr.flatten(order='A'))
print('k : ',arr.flatten(order='K'))

c :  [1 2 3 4]
f :  [1 3 2 4]
a :  [1 2 3 4]
k :  [1 2 3 4]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print('c :', np.ravel(arr,order='C'))
print('f :',np.ravel(arr,order='F'))

c : [1 2 3 4 5 6]
f : [1 4 2 5 3 6]


<h1>16. Numpy 객체를 저장하고 로드하는 방법</h1>

In [ ]:
arr=np.array([1,2,3,4,5,6])
np.save('저장',arr)

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([1,2,3,4,5,6])
np.savez('저장2.npz',arr1,arr2)

In [ ]:
c_arr=np.array([1,2,3,4,5,6,7,8])
np.savetxt('저장3.csv',c_arr)

In [ ]:
l_arr=np.load('./저장.npy')
print(l_arr)
l_arr2=np.load('./저장2.npz')
print(l_arr2)

[1 2 3 4 5 6]


In [ ]:
arr_0=np.load('./저장2.npz')['arr_0']
print(arr_0)

[1 2 3]


In [ ]:
arr_t=np.loadtxt('저장3.csv')
print(arr_t)

[1. 2. 3. 4. 5. 6. 7. 8.]


<h1>17. Pandas란 </h1>
<h1>18. 시리즈와 데이터 프레임</h1>

In [ ]:
import pandas as pd

In [ ]:
s=pd.Series([1,3,5,6,8])
print(s)
print('---------------------')
s1=pd.Series([1,3,5,6,7],index=['하나','둘','셋','넷','다섯'])
print(s1)

0    1
1    3
2    5
3    6
4    8
dtype: int64
---------------------
하나    1
둘     3
셋     5
넷     6
다섯    7
dtype: int64


In [ ]:
#list -> Series데이터
list_data=[1,2,3,4,5]
series=pd.Series(list_data)
print(series)
print('\n')
list_index=['하나','둘','셋','넷','다섯']
new_series=pd.Series(list_data,index=list_index)
print(new_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


하나    1
둘     2
셋     3
넷     4
다섯    5
dtype: int64


In [ ]:
#tuple -> Series데이터
tuple_data=('판','다','스','꿀','잼')
series=pd.Series(tuple_data)
print(series)
print('|n')

tuple_index=('하나','둘','셋','넷','다섯')
new_series=pd.Series(tuple_data,index=tuple_index)
print(new_series)

0    판
1    다
2    스
3    꿀
4    잼
dtype: object
|n
하나    판
둘     다
셋     스
넷     꿀
다섯    잼
dtype: object


In [ ]:
dict_data={'a':1,'b':2,'c':3}
sr=pd.Series(dict_data)
print(dict_data)
print('\n')
print(type(sr))
print('\n')
print(sr)

{'a': 1, 'b': 2, 'c': 3}


<class 'pandas.core.series.Series'>


a    1
b    2
c    3
dtype: int64


In [ ]:
series_data=pd.Series(['홍길동','26','010-777-7777','광주','학생'],
                      index=['이름','나이','전화번호','거주지','직업'])
#정수형 위치 index로 가져오기
n_index=series_data[2]
print(n_index)
print('\n')
#index이름으로 가져오기
n_index=series_data['이름']
print(n_index)
print('\n')
print('전체 데이터 프레임 입니다.')
print(series_data)

010-777-7777


홍길동


전체 데이터 프레임 입니다.
이름               홍길동
나이                26
전화번호    010-777-7777
거주지               광주
직업                학생
dtype: object


In [ ]:
series_data=pd.Series(['홍길동','26','010-777-7777','광주','학생'],
                      index=['이름','나이','전화번호','거주지','직업'])
new=series_data[[0,1,3]]
print(new)
print('\n')
new=series_data[['이름','거주지','직업']]
print(new)

이름     홍길동
나이      26
거주지     광주
dtype: object


이름     홍길동
거주지     광주
직업      학생
dtype: object


In [ ]:
series_data=pd.Series(['홍길동','26','010-777-7777','광주','학생'],
                      index=['이름','나이','전화번호','거주지','직업'])
new=series_data[2:4]
print(new)
print('\n')
new=series_data['나이':'거주지']
print(new)

전화번호    010-777-7777
거주지               광주
dtype: object


나이                26
전화번호    010-777-7777
거주지               광주
dtype: object


In [ ]:
#Series 속성 관련 함수들
new_series=pd.Series(['welcome','to','pandas'],index=['here','is','Gwangju'])
print(new_series.index)
print(new_series.values)

Index(['here', 'is', 'Gwangju'], dtype='object')
['welcome' 'to' 'pandas']


<h2>Pandas-Data Frame</h2>
Data Frame을 만들 때는 2차원 데이터, index, column 3가지가 필요

In [ ]:
list_data_2d=[[23,'남','부산'],[21,'여','서울'],[25,'남','광주'],[27,'여','대전'],[24,'여','광주']]
df=pd.DataFrame(list_data_2d,columns=['나이','성별','지역'])
print(df)
print('\n')
df=pd.DataFrame(list_data_2d,index=['상우','지원','민기','정민','수림'],columns=['나이','성별','지역'])
print(df)

   나이 성별  지역
0  23  남  부산
1  21  여  서울
2  25  남  광주
3  27  여  대전
4  24  여  광주


    나이 성별  지역
상우  23  남  부산
지원  21  여  서울
민기  25  남  광주
정민  27  여  대전
수림  24  여  광주


In [ ]:
tuple_data_2d=((23,'남','부산'),(21,'여','서울'),(25,'남','광주'),(27,'여','대전'),(24,'여','광주'))
df=pd.DataFrame(tuple_data_2d,columns=['나이','성별','지역'])
print(df)
print('\n')
df=pd.DataFrame(tuple_data_2d,index=['상우','지원','민기','정민','수림'],columns=['나이','성별','지역'])
print(df)

   나이 성별  지역
0  23  남  부산
1  21  여  서울
2  25  남  광주
3  27  여  대전
4  24  여  광주


    나이 성별  지역
상우  23  남  부산
지원  21  여  서울
민기  25  남  광주
정민  27  여  대전
수림  24  여  광주


In [ ]:
dict_data={'나이':[23,21,25,27,24],'성별':['남','여','남','여','여'],'지역':['부산','서울','광주','대전','광주']}
df=pd.DataFrame(dict_data)
print(df)
print('\n')
df=pd.DataFrame(dict_data,index=['상우','지원','민기','정민','수림'])
print(df)

   나이 성별  지역
0  23  남  부산
1  21  여  서울
2  25  남  광주
3  27  여  대전
4  24  여  광주


    나이 성별  지역
상우  23  남  부산
지원  21  여  서울
민기  25  남  광주
정민  27  여  대전
수림  24  여  광주


19. 특정 데이터 선택하기

In [ ]:
#열선택
test_data={'팀이름':['아자아자','할수있다','AI마피아','TF고수','경사하강법','광인사'],
           '창의성':['상','중','하','상','중','하'],
           '완성도':[100,80,70,90,50,60],
           '사업성':['좋음','보통','부족','보통','잘함','못함']}
df=pd.DataFrame(test_data)
df

팀이름 창의성  완성도 사업성
0   아자아자   상  100  좋음
1   할수있다   중   80  보통
2  AI마피아   하   70  부족
3   TF고수   상   90  보통
4  경사하강법   중   50  잘함
5    광인사   하   60  못함

In [ ]:
print(df['팀이름'])
print(df['사업성'])
print('\n')
print(df.팀이름)
print(df.사업성)
df[['팀이름','사업성']]

0     아자아자
1     할수있다
2    AI마피아
3     TF고수
4    경사하강법
5      광인사
Name: 팀이름, dtype: object
0    좋음
1    보통
2    부족
3    보통
4    잘함
5    못함
Name: 사업성, dtype: object


0     아자아자
1     할수있다
2    AI마피아
3     TF고수
4    경사하강법
5      광인사
Name: 팀이름, dtype: object
0    좋음
1    보통
2    부족
3    보통
4    잘함
5    못함
Name: 사업성, dtype: object


팀이름 사업성
0   아자아자  좋음
1   할수있다  보통
2  AI마피아  부족
3   TF고수  보통
4  경사하강법  잘함
5    광인사  못함

In [ ]:
#행 선택
test_data={'팀이름':['아자아자','할수있다','AI마피아','TF고수','경사하강법','광인사'],
           '창의성':['상','중','하','상','중','하'],
           '완성도':[100,80,70,90,50,60],
           '사업성':['좋음','보통','부족','보통','잘함','못함']}
df=pd.DataFrame(test_data,index=['11팀','12팀','13팀','14팀','15팀','16팀'])
print(df.loc[['13팀']])
print(df.iloc[[1]])
print('=====================================')

df.loc[['11팀','14팀']]
print('\n')
df.iloc[[2,5]]

print('\n')
df.loc['12팀':'14팀']
df.iloc[1:5]

print('\n')
df.loc['12팀'::2]
df.iloc[1::2]

       팀이름 창의성  완성도 사업성
13팀  AI마피아   하   70  부족
      팀이름 창의성  완성도 사업성
12팀  할수있다   중   80  보통








팀이름 창의성  완성도 사업성
12팀  할수있다   중   80  보통
14팀  TF고수   상   90  보통
16팀   광인사   하   60  못함

In [ ]:
#원소 선택
test_data={'이름':['상우','현정','문영','동엽','우제'],
           '국어':[85,88,90,50,70],
           '수학':[57,90,100,78,66],
           '영어':[85,89,67,98,98],
           '과학':[93,79,92,50,70],
           '체육':[94,80,99,69,100]}
df=pd.DataFrame(test_data)
df.set_index('이름',inplace=True)    #'이름'을 index로 설정
df

국어   수학  영어  과학   체육
이름                      
상우  85   57  85  93   94
현정  88   90  89  79   80
문영  90  100  67  92   99
동엽  50   78  98  50   69
우제  70   66  98  70  100

In [ ]:
df.loc[['문영'],['영어']]

영어
이름    
문영  67

In [ ]:
df.iloc[[1],[1]]

수학
이름    
현정  90

In [ ]:
df.loc[['문영'],['국어','체육']]

국어  체육
이름        
문영  90  99

In [ ]:
df.iloc[[2],[0,3]]

국어  과학
이름        
문영  90  92

In [ ]:
df.loc[['문영','동엽'],['국어']]

국어
이름    
문영  90
동엽  50

In [ ]:
df.iloc[[1,3],[0,2,4]]

국어  영어  체육
이름            
현정  88  89  80
동엽  50  98  69

20.Index활용

In [ ]:
test_data={'이름':['상우','현정','문영','동엽','우제'],
           '국어':[85,88,90,50,70],
           '수학':[57,90,100,78,66],
           '영어':[85,89,67,98,98],
           '과학':[93,79,92,50,70],
           '체육':[94,80,99,69,100]}
df=pd.DataFrame(test_data)
df

이름  국어   수학  영어  과학   체육
0  상우  85   57  85  93   94
1  현정  88   90  89  79   80
2  문영  90  100  67  92   99
3  동엽  50   78  98  50   69
4  우제  70   66  98  70  100

In [ ]:
df['체육']=90
df['사회']=[89,69,79,80,100]
df

이름  국어   수학  영어  과학  체육   사회
0  상우  85   57  85  93  90   89
1  현정  88   90  89  79  90   69
2  문영  90  100  67  92  90   79
3  동엽  50   78  98  50  90   80
4  우제  70   66  98  70  90  100

In [ ]:
df.loc[5]=100
df.loc[6]=['jack',90,100,92,93,95,96]
df.loc['일곱']=['Michael',71,72,75,76,74,73]
df

이름   국어   수학   영어   과학   체육   사회
0        상우   85   57   85   93   90   89
1        현정   88   90   89   79   90   69
2        문영   90  100   67   92   90   79
3        동엽   50   78   98   50   90   80
4        우제   70   66   98   70   90  100
5       100  100  100  100  100  100  100
6      jack   90  100   92   93   95   96
일곱  Michael   71   72   75   76   74   73

In [ ]:
test_data={'상호명':['상우네','현정이네','문영이네','동엽이네','우제네'],
           '사과':[850,880,900,500,700],
           '배':[570,900,1000,780,660],
           '딸기':[850,890,670,980,908],
           '포도':[930,790,920,500,700]}
df=pd.DataFrame(test_data)
print(df)

new_df1=df.set_index('상호명')
print(new_df1)

new_df2=df.set_index(['사과'])
print(new_df2)

df.set_index(['상호명'],inplace=True)
df

    상호명   사과     배   딸기   포도
0   상우네  850   570  850  930
1  현정이네  880   900  890  790
2  문영이네  900  1000  670  920
3  동엽이네  500   780  980  500
4   우제네  700   660  908  700
       사과     배   딸기   포도
상호명                      
상우네   850   570  850  930
현정이네  880   900  890  790
문영이네  900  1000  670  920
동엽이네  500   780  980  500
우제네   700   660  908  700
      상호명     배   딸기   포도
사과                       
850   상우네   570  850  930
880  현정이네   900  890  790
900  문영이네  1000  670  920
500  동엽이네   780  980  500
700   우제네   660  908  700


사과     배   딸기   포도
상호명                      
상우네   850   570  850  930
현정이네  880   900  890  790
문영이네  900  1000  670  920
동엽이네  500   780  980  500
우제네   700   660  908  700

In [ ]:
df1=pd.DataFrame(test_data,index=[4,2,1,0,3])
print(df1)
print('\n')

new_index=[0,1,2,3,4,5]
reindex_df1=df1.reindex(new_index)
print(reindex_df1)

#fill_value로 NaN 데이터 채우기
reindex_df2=df1.reindex(new_index,fill_value=777)
reindex_df2

    상호명   사과     배   딸기   포도
4   상우네  850   570  850  930
2  현정이네  880   900  890  790
1  문영이네  900  1000  670  920
0  동엽이네  500   780  980  500
3   우제네  700   660  908  700


    상호명     사과       배     딸기     포도
0  동엽이네  500.0   780.0  980.0  500.0
1  문영이네  900.0  1000.0  670.0  920.0
2  현정이네  880.0   900.0  890.0  790.0
3   우제네  700.0   660.0  908.0  700.0
4   상우네  850.0   570.0  850.0  930.0
5   NaN    NaN     NaN    NaN    NaN


상호명   사과     배   딸기   포도
0  동엽이네  500   780  980  500
1  문영이네  900  1000  670  920
2  현정이네  880   900  890  790
3   우제네  700   660  908  700
4   상우네  850   570  850  930
5   777  777   777  777  777

In [ ]:
reindex_df2.set_index('상호명',inplace=True)
reindex_df2.reset_index()

상호명   사과     배   딸기   포도
0  동엽이네  500   780  980  500
1  문영이네  900  1000  670  920
2  현정이네  880   900  890  790
3   우제네  700   660  908  700
4   상우네  850   570  850  930
5   777  777   777  777  777

In [ ]:
test_data={'상호명':['상우네','현정이네','문영이네','동엽이네','우제네'],
           '사과':[850,880,900,500,700],
           '배':[570,900,1000,780,660],
           '딸기':[850,890,670,980,908],
           '포도':[930,790,920,500,700]}
df=pd.DataFrame(test_data,index=[4,2,1,0,3])
print(df)
print('\n')
sorted_df=df.sort_index()
print(sorted_df)
print('\n')

#오름차순 True, 내림차순 False
ascending_df=df.sort_index(ascending=True)
print(ascending_df)
descending_df=df.sort_index(ascending=False)
descending_df

    상호명   사과     배   딸기   포도
4   상우네  850   570  850  930
2  현정이네  880   900  890  790
1  문영이네  900  1000  670  920
0  동엽이네  500   780  980  500
3   우제네  700   660  908  700


    상호명   사과     배   딸기   포도
0  동엽이네  500   780  980  500
1  문영이네  900  1000  670  920
2  현정이네  880   900  890  790
3   우제네  700   660  908  700
4   상우네  850   570  850  930


    상호명   사과     배   딸기   포도
0  동엽이네  500   780  980  500
1  문영이네  900  1000  670  920
2  현정이네  880   900  890  790
3   우제네  700   660  908  700
4   상우네  850   570  850  930


상호명   사과     배   딸기   포도
4   상우네  850   570  850  930
3   우제네  700   660  908  700
2  현정이네  880   900  890  790
1  문영이네  900  1000  670  920
0  동엽이네  500   780  980  500

In [ ]:
#행,열 삭제
test_data={'상호명':['상우네','현정이네','문영이네','동엽이네','우제네'],
           '사과':[850,880,900,500,700],
           '배':[570,900,1000,780,660],
           '딸기':[850,890,670,980,908],
           '포도':[930,790,920,500,700]}
df=pd.DataFrame(test_data)
df.set_index('상호명',inplace=True)
print(df)

ndf1=df.drop('사과',axis=1)
print(ndf1)

ndf2=df.drop(['사과','딸기'],axis=1)
print(ndf2)

ndf3=df.drop('상우네')
print(ndf3)

ndf4=df.drop(['현정이네','문영이네'])
ndf4

       사과     배   딸기   포도
상호명                      
상우네   850   570  850  930
현정이네  880   900  890  790
문영이네  900  1000  670  920
동엽이네  500   780  980  500
우제네   700   660  908  700
         배   딸기   포도
상호명                 
상우네    570  850  930
현정이네   900  890  790
문영이네  1000  670  920
동엽이네   780  980  500
우제네    660  908  700
         배   포도
상호명            
상우네    570  930
현정이네   900  790
문영이네  1000  920
동엽이네   780  500
우제네    660  700
       사과     배   딸기   포도
상호명                      
현정이네  880   900  890  790
문영이네  900  1000  670  920
동엽이네  500   780  980  500
우제네   700   660  908  700


사과    배   딸기   포도
상호명                     
상우네   850  570  850  930
동엽이네  500  780  980  500
우제네   700  660  908  700

21. Pandas Data 입출력

In [ ]:
df=pd.read_csv('키.csv')
df

민지  15
0     홍  16
1  choi  15
2     다  16
3     순  17

In [ ]:
data={'이름':['상우','민철','민지'],
      '미적':['A+','B+','C'],
      '물리학':['C+','A+','A'],
      'Python':['A+','B+','A+']}
df=pd.DataFrame(data)
df.set_index('이름',inplace=True)
df.to_csv('./df_tocsv.csv')
df

미적 물리학 Python
이름               
상우  A+  C+     A+
민철  B+  A+     B+
민지   C   A     A+

In [ ]:
data={"이름":{"1번":"상우","2번":"민성","3번":"지현"},
 "나이":{"1번":26,"2번":22,"3번":24},
 "취미":{"1번":"서핑","2번":"독서","3번":"자전거"},
 "거주지":{"1번":"부산","2번":"대전","3번":"광주"}}
df=pd.DataFrame(data)
df.to_json('./tojson.json')

In [ ]:
df=pd.read_json('tojson.json')
print(df)
df.set_index('이름',inplace=True)
df

    이름  나이   취미 거주지
1번  상우  26   서핑  부산
2번  민성  22   독서  대전
3번  지현  24  자전거  광주


나이   취미 거주지
이름             
상우  26   서핑  부산
민성  22   독서  대전
지현  24  자전거  광주

22.Pandas 연산

In [ ]:
dict_data={'c0':[1,2,3],'c1':[4,5,6],
           'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,15]}
df=pd.DataFrame(dict_data)
add = df + 10
print(add)
print('\n')
sub=df-10
print(sub)
print('\n')
mul=df*10
print(mul)
print('\n')
div=df/10
print(div)

   c0  c1  c2  c3  c4
0  11  14  17  20  23
1  12  15  18  21  24
2  13  16  19  22  25


   c0  c1  c2  c3  c4
0  -9  -6  -3   0   3
1  -8  -5  -2   1   4
2  -7  -4  -1   2   5


   c0  c1  c2   c3   c4
0  10  40  70  100  130
1  20  50  80  110  140
2  30  60  90  120  150


    c0   c1   c2   c3   c4
0  0.1  0.4  0.7  1.0  1.3
1  0.2  0.5  0.8  1.1  1.4
2  0.3  0.6  0.9  1.2  1.5


In [ ]:
data_1={'c0':[1,2,3],'c1':[4,5,6],
           'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,15]}
data_2={'c0':[1,2,3],'c1':[4,5,6],
           'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,np.nan]}
df_1=pd.DataFrame(data_1)
df_2=pd.DataFrame(data_2)
df_1+df_2

c0  c1  c2  c3    c4
0   2   8  14  20  26.0
1   4  10  16  22  28.0
2   6  12  18  24   NaN

23. Pandas 간단한 통계 메소드

In [ ]:
import random
data_1=[]
data_2=[]
for i in range(0,10):
  data_1.append(random.uniform(0,1))     #uniform : 0부터 1사이의 수를 랜덤하게 꺼냄
for i in range(0,10):
  data_2.append(random.uniform(0,2))
dict_data={'first':data_1,'second':data_2 }
index_data=['zero','1st','2nd','3rd','4th','5th','6th','7th','8th','9th']
df=pd.DataFrame(dict_data, index=index_data)
print(df)
print('\n')

#평균
mean_val=df.mean()
first_mean=df['first'].mean()
print('first 평균 : ',first_mean)
second_mean=df['second'].mean()
print('second 평균 :',second_mean)
print('\n')
print('--------------')
#중간값
median_val=df.median()
first_median=df['first'].median()
second_median=df['second'].median()
print(median_val)
print('\n')
print('first 중간값 : ',first_median)
print('second 중간값 : ',second_median)

         first    second
zero  0.245741  0.149061
1st   0.555112  0.353520
2nd   0.996736  0.330660
3rd   0.341520  0.962129
4th   0.052424  1.168088
5th   0.901218  0.377830
6th   0.266743  1.672311
7th   0.291177  0.401993
8th   0.101730  0.546968
9th   0.258342  1.775816


first 평균 :  0.401074297691381
second 평균 : 0.7738376690891366


--------------
first     0.278960
second    0.474481
dtype: float64


first 중간값 :  0.2789599741107018
second 중간값 :  0.47448076095760294


In [ ]:
#최댓값
max_val=df.max()
print(max_val)
print('\n')
first_max=df['first'].max()
print(first_max)
second_max=df['second'].max()
print(second_max)

print('================')
#최솟값
min_val=df.min()
first_min=df['first'].min()
second_min=df['second'].min()
print(min_val)
print('\n')
print('first 최솟값',first_min)
print('second 최솟값',second_min)

first     0.996736
second    1.775816
dtype: float64


0.9967360696628406
1.775816124498448
first     0.052424
second    0.149061
dtype: float64


first 최솟값 0.05242425014566554
second 최솟값 0.14906070468986377


In [ ]:
#표준편차
std_val=df.std()
first_std=df['first'].std()
second_std=df['second'].std()
print(std_val)
print('\n')
print(f'first 표준편차 : {first_std}')
print(f'second 표준편차 : {second_std}')

first     0.319378
second    0.588036
dtype: float64


first 표준편차 : 0.31937766203492524
second 표준편차 : 0.5880364736425349


In [ ]:
#상관계수
data_3=[]
for i in range(0,10):
  data_3.append(random.uniform(0,2))
dict_data={'first':data_1,
           'second':data_2,
           'third':data_3}
index_data=['zero','1st','2nd','3rd','4th','5th','6th','7th','8th','9th']
ndf=pd.DataFrame(dict_data,index=index_data)
print(ndf)
print('=====================================')
corr_val=ndf.corr()
print(corr_val)
print('\n')
first_third_corr=ndf[['first','third']].corr()
first_third_corr

         first    second     third
zero  0.245741  0.149061  1.632836
1st   0.555112  0.353520  1.147453
2nd   0.996736  0.330660  0.283010
3rd   0.341520  0.962129  0.065241
4th   0.052424  1.168088  1.568427
5th   0.901218  0.377830  1.562516
6th   0.266743  1.672311  0.092588
7th   0.291177  0.401993  1.663506
8th   0.101730  0.546968  0.887305
9th   0.258342  1.775816  0.203202
           first    second     third
first   1.000000 -0.433865 -0.084446
second -0.433865  1.000000 -0.588788
third  -0.084446 -0.588788  1.000000




first     third
first  1.000000 -0.084446
third -0.084446  1.000000

24.pandas 활용 기초

In [ ]:
#누락데이터 NaN(Not a Number)
import seaborn as sns
df=sns.load_dataset('titanic')
print(df.tail())
print('\n')

#info(), value_counts()
print(df.info())
print('\n')
print('-----------------------=--============================---------')
nan_df=df['deck'].value_counts(dropna=False)
print(nan_df)

print('=============================================================')
#isnull(),notnull()
print(df.head().isnull())    #원소가 NaN데이터일 경우 True 반환,유효 데이터일 경우 False
df.head().notnull()   #Nan데이터일 경우 False 반환

     survived  pclass     sex   age  ...  deck  embark_town  alive  alone
886         0       2    male  27.0  ...   NaN  Southampton     no   True
887         1       1  female  19.0  ...     B  Southampton    yes   True
888         0       3  female   NaN  ...   NaN  Southampton     no  False
889         1       1    male  26.0  ...     C    Cherbourg    yes   True
890         0       3    male  32.0  ...   NaN   Queenstown     no   True

[5 rows x 15 columns]


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    objec

survived  pclass   sex   age  ...   deck  embark_town  alive  alone
0      True    True  True  True  ...  False         True   True   True
1      True    True  True  True  ...   True         True   True   True
2      True    True  True  True  ...  False         True   True   True
3      True    True  True  True  ...   True         True   True   True
4      True    True  True  True  ...  False         True   True   True

[5 rows x 15 columns]

In [ ]:
#dropna(), thresh 옵션 : 누락 데이터가 전체 데이터 개수의 절반을 넘는 열을 제거
print(df.isnull().sum(axis=0))
print('\n')
ndf=df.dropna(axis=1,thresh=445)
print(ndf.columns)
print('---------------------------')
#dropna(), how옵션 : NaN데이터가 존재하는 모든 행 제거
ndf2=ndf.dropna(subset=['age'],how='any',axis=0) 
print(ndf2.isnull().sum(axis=0))
print('\n')
print(ndf2.notnull().sum(axis=0))

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64


Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')
---------------------------
survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64


survived       714
pclass         714
sex            714
age            714
sibsp          714
parch          714
fare           714
embarked       712
class          714
who            714
adult_male     714
embark_town    712
alive     

In [ ]:
#누락 데이터 채우기
df.dropna(axis=1,thresh=445,inplace=True)
age_median=df['age'].median(axis=0)
df['age'].fillna(age_median,inplace=True)
df.isnull().sum(axis=0)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       2
class          0
who            0
adult_male     0
embark_town    2
alive          0
alone          0
dtype: int64

In [ ]:
#중복데이터 확인,제거
data={'c0':['a','a','c','d','e','f','c'],
      'c1':[1,1,2,3,4,5,2],
      'c2':[1,1,2,3,4,5,2],
      'c3':['a','a','c','d','e','f','c']}
df=pd.DataFrame(data)
duplicated_df=df.duplicated()   #duplicated()는 이전의 행과 비교하여 중복되는 행일 경우 True, 처음 나오는 행은 False
print(duplicated_df)
df.drop_duplicates(inplace=True)
df

0    False
1     True
2    False
3    False
4    False
5    False
6     True
dtype: bool


c0  c1  c2 c3
0  a   1   1  a
2  c   2   2  c
3  d   3   3  d
4  e   4   4  e
5  f   5   5  f

In [ ]:
#시계열 데이터
import pandas as pd
corona_df=pd.read_csv('PatientRoute.csv')
corona_df.head()

patient_id  global_num  ...   latitude   longitude
0  1000000001         2.0  ...  37.615246  126.715632
1  1000000001         2.0  ...  37.567241  127.005659
2  1000000002         5.0  ...  37.592560  127.017048
3  1000000002         5.0  ...  37.591810  127.016822
4  1000000002         5.0  ...  37.563992  127.029534

[5 rows x 8 columns]

In [ ]:
#to_datetime() : 데이터를 Timestamp객체로 바꿔서 
corona_df['new_date']=pd.to_datetime(corona_df['date'])
print(corona_df.info())
corona_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6714 entries, 0 to 6713
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   patient_id  6714 non-null   int64         
 1   global_num  3571 non-null   float64       
 2   date        6714 non-null   object        
 3   province    6714 non-null   object        
 4   city        6714 non-null   object        
 5   type        6714 non-null   object        
 6   latitude    6714 non-null   float64       
 7   longitude   6714 non-null   float64       
 8   new_data    6714 non-null   datetime64[ns]
 9   new_date    6714 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(3), int64(1), object(4)
memory usage: 524.7+ KB
None


patient_id  global_num        date  ...   longitude   new_data   new_date
0  1000000001         2.0  2020-01-22  ...  126.715632 2020-01-22 2020-01-22
1  1000000001         2.0  2020-01-24  ...  127.005659 2020-01-24 2020-01-24
2  1000000002         5.0  2020-01-25  ...  127.017048 2020-01-25 2020-01-25
3  1000000002         5.0  2020-01-26  ...  127.016822 2020-01-26 2020-01-26
4  1000000002         5.0  2020-01-26  ...  127.029534 2020-01-26 2020-01-26

[5 rows x 10 columns]

In [ ]:
#to_period() : Timestamp객체를 일정 기간을 나타내는 Period 객체로 바꿀 수 있음, freq옵션을 사용하여 반복되는 기간 설정
#freq='D'1일, freq='M'1달, freq='A'1년
data=corona_df['new_date'].dt
freq_d=data.to_period(freq='D')
freq_m=data.to_period(freq='M')
freq_a=data.to_period(freq='A')
print(freq_d)
print('--------=-=-=--=-')
print(freq_m)
print(']========================[')
print(freq_a)

0       2020-01-22
1       2020-01-24
2       2020-01-25
3       2020-01-26
4       2020-01-26
           ...    
6709    2020-03-24
6710    2020-03-24
6711    2020-03-25
6712    2020-03-25
6713    2020-03-25
Name: new_date, Length: 6714, dtype: period[D]
--------=-=-=--=-
0       2020-01
1       2020-01
2       2020-01
3       2020-01
4       2020-01
         ...   
6709    2020-03
6710    2020-03
6711    2020-03
6712    2020-03
6713    2020-03
Name: new_date, Length: 6714, dtype: period[M]
]========================[
0       2020
1       2020
2       2020
3       2020
4       2020
        ... 
6709    2020
6710    2020
6711    2020
6712    2020
6713    2020
Name: new_date, Length: 6714, dtype: period[A-DEC]


In [ ]:
#날짜 데이터 분리
#dt.day, dt.month, dt.year
corona_df['Year']=corona_df['new_date'].dt.year
corona_df['Month']=corona_df['new_date'].dt.month
corona_df['Day']=corona_df['new_date'].dt.day
corona_df.head()

patient_id  global_num        date     province  ...   new_date  Year  Month  Day
0  1000000001         2.0  2020-01-22  Gyeonggi-do  ... 2020-01-22  2020      1   22
1  1000000001         2.0  2020-01-24        Seoul  ... 2020-01-24  2020      1   24
2  1000000002         5.0  2020-01-25        Seoul  ... 2020-01-25  2020      1   25
3  1000000002         5.0  2020-01-26        Seoul  ... 2020-01-26  2020      1   26
4  1000000002         5.0  2020-01-26        Seoul  ... 2020-01-26  2020      1   26

[5 rows x 13 columns]

In [ ]:
#날짜 인덱스 활용
corona_df=pd.read_csv('PatientRoute.csv')
corona_df['new_date']=pd.to_datetime(corona_df['date'])
corona_df.set_index('new_date',inplace=True)
corona_df

patient_id  global_num  ...   latitude   longitude
new_date                            ...                       
2020-01-22  1000000001         2.0  ...  37.615246  126.715632
2020-01-24  1000000001         2.0  ...  37.567241  127.005659
2020-01-25  1000000002         5.0  ...  37.592560  127.017048
2020-01-26  1000000002         5.0  ...  37.591810  127.016822
2020-01-26  1000000002         5.0  ...  37.563992  127.029534
...                ...         ...  ...        ...         ...
2020-03-24  6100000090         NaN  ...  37.558654  126.794474
2020-03-24  6100000090         NaN  ...  35.173220  128.946459
2020-03-25  6100000090         NaN  ...  35.336944  129.026389
2020-03-25  6100000090         NaN  ...  35.335757  129.025003
2020-03-25  6100000090         NaN  ...  35.336944  129.026389

[6714 rows x 8 columns]

In [ ]:
#데이터 추출
corona_df_ym=corona_df.loc['2020-02']
print(corona_df_ym)
print('\n')
corona_df_ym_cols=corona_df.loc['2020-02','city':'longitude']
print(corona_df_ym_cols)
print('\n')
corona_df_ymd_range=corona_df.loc['2020-02-22':'2020-02-23']
print(corona_df_ymd_range)

            patient_id  global_num  ...   latitude   longitude
new_date                            ...                       
2020-02-01  1000000009        19.0  ...  37.498450  127.107250
2020-02-01  1000000009        19.0  ...  37.381479  126.657175
2020-02-01  1000000009        19.0  ...  37.381479  126.657175
2020-02-03  1000000009        19.0  ...  37.382699  127.118906
2020-02-03  1000000009        19.0  ...  37.377139  127.112750
...                ...         ...  ...        ...         ...
2020-02-27  6100000070         NaN  ...  35.542636  128.492066
2020-02-27  6100000070         NaN  ...  35.542636  128.492066
2020-02-27  6100000070         NaN  ...  35.541315  128.500770
2020-02-22  6100000083         NaN  ...  35.871435  128.601445
2020-02-22  6100000083         NaN  ...  34.856049  128.725042

[3206 rows x 8 columns]


                       city        type   latitude   longitude
new_date                                                      
2020-02-01        Songpa-gu 

In [ ]:
import pandas as pd
with open('html_source.txt','r')as f:
  tt=f.read()
  t1=tt.split('<div class="inner_number">')
  print(t1)
  t1.pop(0)
tip=[]
for i in t1:
  tip.append(i.split('</div>')[0])
print(tip)

['<html lang="ko"><head>\n\t<title>카페</title>\n\t\n\n\n\n<meta name="robots" content="noindex, nofollow">\n<meta http-equiv="Content-Type" content="text/html;charset=KSC5601">\n<meta http-equiv="X-UA-Compatible" content="requiresActiveX=true">\n\n\n\n<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?2">\n<meta name="referrer" content="always">\n\n\n\n <script>\nvar g_sUserId = "";\nvar g_sGroupId = "false";\nvar g_sCafeHome = "https://cafe.naver.com/" + "fingerstyle";\nvar g_sClubId = "10174263";\nvar g_mobileWebLink = "https://m.cafe.naver.com/fingerstyle";\n\nvar g_sCafeThumbUrl = \'https://cafethumb.pstatic.net\';\nvar g_sUpcafeUrl = \'https://up.cafe.naver.com\';\nvar g_sCafeUrl = "https://cafe.naver.com";\nvar g_sCafeUrlOnly = "fingerstyle";\nvar g_sCafeImgUrl = \'https://cafe.pstatic.net\';\nvar g_sCafeFileUrl = \'https://cafefiles.pstatic.net\';\nvar g_sItem2Url = \'https://item2.naver.com\';\nvar g_sLoginUrl = "http://nid.naver.com";\nvar g_sNidHttps = \'https://

In [ ]:
pd_arr=pd.Series(tip)
print(pd_arr)

0     223778
1     223773
2     223772
3     223769
4     223767
5     223760
6     223757
7     223755
8     223753
9     223751
10    223743
11    223738
12    223736
13    223728
14    223715
dtype: object


In [ ]:
with open ('html_source.txt','r') as f:
  tt2=f.read()
  t2=tt2.split('<a class="article')
  t2.pop(0)
title=[]
for i in t2:
  i2=i.split('</a>')[0]
  title.append(i2.split('>')[-1])
#i2.split().split() 가능

title2=[]
for k in title:
  t3=k.replace('\n','')
  t4=t3.replace(' ','')
  title2.append(t4)

print(title2)

print('\n')
pd_arr2=pd.Series(title2)
print(pd_arr2)

['YuhkiKuramoto-Meditation', 'CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)', 'Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)', 'IraisemyhandshightotheLord(내손을주께높이듭니다)', '아이유가을아침기타커버!', 'GIN-Recollection(cover)', 'EdGerhard-TheWaterisWide/Cover', '비틀즈의IWill연주해보았습니다.', 'TommyEmmanuel-Closetoyou커버', 'BTS(방탄소년단)-Butter쳐봤습니다!!', '[뽕용Live]KotaroOshio-Twilight(Livestage/coverby기타치는뽕용)', 'Creep편곡', '양희은아이유-가을아침기타커버입니다!', '쾌지나칭칭나네편곡', 'DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)']


0                              YuhkiKuramoto-Meditation
1             CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)
2       Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)
3                IraisemyhandshightotheLord(내손을주께높이듭니다)
4                                          아이유가을아침기타커버!
5                               GIN-Recollection(cover)
6                        EdGerhard-TheWaterisWide/Cover
7                                    비틀즈의IWill연주해보았습니다.
8                            TommyEmmanuel-Closetoyou커버
9            

In [ ]:
pd_arr3=pd.DataFrame(title2,index=tip,columns=['<노래제목>'])
print(pd_arr3)

                                                   <노래제목>
223778                           YuhkiKuramoto-Meditation
223773          CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)
223772    Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)
223769             IraisemyhandshightotheLord(내손을주께높이듭니다)
223767                                       아이유가을아침기타커버!
223760                            GIN-Recollection(cover)
223757                     EdGerhard-TheWaterisWide/Cover
223755                                 비틀즈의IWill연주해보았습니다.
223753                         TommyEmmanuel-Closetoyou커버
223751                           BTS(방탄소년단)-Butter쳐봤습니다!!
223743  [뽕용Live]KotaroOshio-Twilight(Livestage/coverby...
223738                                            Creep편곡
223736                                양희은아이유-가을아침기타커버입니다!
223728                                          쾌지나칭칭나네편곡
223715  DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)


In [ ]:
pd_arr3.reset_index()

index                                             <노래제목>
0   223778                           YuhkiKuramoto-Meditation
1   223773          CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)
2   223772    Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)
3   223769             IraisemyhandshightotheLord(내손을주께높이듭니다)
4   223767                                       아이유가을아침기타커버!
5   223760                            GIN-Recollection(cover)
6   223757                     EdGerhard-TheWaterisWide/Cover
7   223755                                 비틀즈의IWill연주해보았습니다.
8   223753                         TommyEmmanuel-Closetoyou커버
9   223751                           BTS(방탄소년단)-Butter쳐봤습니다!!
10  223743  [뽕용Live]KotaroOshio-Twilight(Livestage/coverby...
11  223738                                            Creep편곡
12  223736                                양희은아이유-가을아침기타커버입니다!
13  223728                                          쾌지나칭칭나네편곡
14  223715  DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)