<a href="https://colab.research.google.com/github/yun-aha/GSTEC/blob/main/210630.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. 딥러닝 & 강화학습

In [ ]:
#MSE
#1
y_1 = 21
y_2 = 10
y_3 = 14
y_hat_1 = 15
y_hat_2 = 12
y_hat_3 = 18

a = (y_1 - y_hat_1)**2
b = (y_2 - y_hat_2)**2
c = (y_3 - y_hat_3)**2
print(a, b, c)

import numpy as np
n = 3
mse = (a+b+c)/n

print("MSE : {}".format(np.round(mse,4)))

36 4 16
MSE : 18.6667


In [ ]:
#MSE
#2
import numpy as np
y=[21,10,14]
yh=[15,12,18]
AI=(y[0]-yh[0])**2+(y[1]-yh[1])**2+(y[2]-yh[2])**2
n=3
mse=AI/n
print(np.round(mse,4))

18.6667


성별 m,f,i를 0,1,2로 변경하면 선형적 문제!  
--> 원핫벡터 One-hot Vector  


In [ ]:
#1
rows=['M',0.455,0.365,0.0950] # -> [1,0,0,0.455,0.365,0.0950]
if rows[0]=='M':
  m=[1,0,0]
  rows.pop(0)
  rows=m+rows
elif rows[0]=='F':
  f=[0,1,0]
  rows.pop(0)
  rows=f+rows
else:
  i=[0,0,1]
  rows=i+rows
print(rows)

[1, 0, 0, 0.455, 0.365, 0.095]


In [ ]:
#2 np.zeros 사용
rows = ['I', 0.455, 0.365, 0.095] # ---->> [1, 0, 0, 0.455, 0.365, 0.095]
data = np.zeros(6)
print(data)
if rows[0] == 'M':
    data[0] = 1
elif rows[0] == 'F':
    data[1] = 1
elif rows[0] == 'I':
    data[2] = 1

print('----------------------')
print(data)
print(rows)
print("=========================")
print(data)

data[3:] = rows[1:]
print(data)

[0. 0. 0. 0. 0. 0.]
----------------------
[0. 0. 1. 0. 0. 0.]
['I', 0.455, 0.365, 0.095]
[0. 0. 1. 0. 0. 0.]
[0.    0.    1.    0.455 0.365 0.095]


In [ ]:
import csv
with open('./abalone_mini.csv') as csvfile:
  csvreader=csv.reader(csvfile)
  
  rows=[]
  for row in csvreader:
    rows.append(row)
print(rows)

[['M', '0.455', '0.365', '0.095', '0.514', '0.2245', '0.101', '0.15', '15'], ['M', '0.35', '0.265', '0.09', '0.2255', '0.0995', '0.0485', '0.07', '7'], ['F', '0.53', '0.42', '0.135', '0.677', '0.2565', '0.1415', '0.21', '9'], ['M', '0.44', '0.365', '0.125', '0.516', '0.2155', '0.114', '0.155', '10'], ['I', '0.33', '0.255', '0.08', '0.205', '0.0895', '0.0395', '0.055', '7']]


In [ ]:
#1
m=[1,0,0]
f=[0,1,0]
i=[0,0,1]
rows_s=[]
for r in rows:
  if r[0]=='M':
    r.pop(0)
    r=m+r
    rows_s.append(r)
  elif r[1]=='F':
    r.pop(0)
    r=f+r
    rows_s.append(r)
  else:
    r.pop(0)
    r=i+r
    rows_s.append(r)
print(rows_s)

[[1, 0, 0, '0.455', '0.365', '0.095', '0.514', '0.2245', '0.101', '0.15', '15'], [1, 0, 0, '0.35', '0.265', '0.09', '0.2255', '0.0995', '0.0485', '0.07', '7'], [0, 0, 1, '0.53', '0.42', '0.135', '0.677', '0.2565', '0.1415', '0.21', '9'], [1, 0, 0, '0.44', '0.365', '0.125', '0.516', '0.2155', '0.114', '0.155', '10'], [0, 0, 1, '0.33', '0.255', '0.08', '0.205', '0.0895', '0.0395', '0.055', '7']]


In [ ]:
#2 
#enumerate함수 사용
data=np.zeros([5,11])
print(data)
for n,row in enumerate(rows):
  if row[0]=='M': data[n,0]=1
  elif row[0]=='F': data[n,1]=1
  elif row[0]=='I': data[n,2]=1
  data[n,3:]=row[1:]
print(data)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 1.      0.      0.      0.455   0.365   0.095   0.514   0.2245  0.101
   0.15   15.    ]
 [ 1.      0.      0.      0.35    0.265   0.09    0.2255  0.0995  0.0485
   0.07    7.    ]
 [ 0.      1.      0.      0.53    0.42    0.135   0.677   0.2565  0.1415
   0.21    9.    ]
 [ 1.      0.      0.      0.44    0.365   0.125   0.516   0.2155  0.114
   0.155  10.    ]
 [ 0.      0.      1.      0.33    0.255   0.08    0.205   0.0895  0.0395
   0.055   7.    ]]


In [ ]:
#함수에 함수 넣기
def main_exec():
  #import_data()
  model_init()
  #train_and_test()

RND_MEAN = 0
RND_STD = 1
def model_init():
  global weight, bias      #전역변수화
  weight = np.random.normal(RND_MEAN,RND_STD,size=1)
  bias = np.random.normal(RND_MEAN,RND_STD,size=1)

main_exec()
print('weight : ',weight)
print('bias : ',bias)

weight :  [1.53771869]
bias :  [-0.65914163]


#2. 머신러닝

In [ ]:
#토너먼트 9팀
#1
import random
t=[1,2,3,4,5,6,7,8,9]
a=[]
while len(t)>0:
  one=random.choice(t)
  t.remove(one)
  if len(t)==0:
    a.append(one)
    break
  two=random.choice(t)
  t.remove(two)
  a.append((one,two))
print(a)

print('===================================')
#2
teams=list(range(1,10))
random.shuffle(teams)
half=len(teams)//2
print(teams[:half], teams[half:])
print(teams)
print(list(zip(teams[:half],teams[half:])))

[(7, 5), (2, 4), (3, 8), (9, 1), 6]
[7, 6, 5, 3] [8, 1, 4, 9, 2]
[7, 6, 5, 3, 8, 1, 4, 9, 2]
[(7, 8), (6, 1), (5, 4), (3, 9)]


In [ ]:
#html 배포 -> https://app.netlify.com/teams/yun-aha/overview
#깃헙 연동
#web을 배포하면 default로 찾는 폴더 index.html

#3. 빅데이터 분석

괄호x
결측치 여부는 IS NULL


#4. 취업멘토링

* CB insights  
* classum  
* g3cloud  
* Crunchbase: Discover innovative companies and the people ...https://www.crunchbase.com

