<a href="https://colab.research.google.com/github/yun-aha/GSTEC/blob/main/210623_210624.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>14. 배열을 뒤집는 방법<h1>

In [ ]:
#np.flip
import numpy as np
print('1차원 배열')
arr=np.array([1,2,3,4,5,6,7,8])
arr1=np.flip(arr)
print(arr1)
print('2차원 배열 뒤집기')
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr11=np.flip(arr)
print(arr11)
print('axis=0')
arr111=np.flip(arr,axis=0)
print(arr111)
print('axis=1')
arr1111=np.flip(arr,axis=1)
print(arr1111)

1차원 배열
[8 7 6 5 4 3 2 1]
2차원 배열 뒤집기
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
axis=0
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
axis=1
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


<h1>15. n차원 배열 재구성 및 flatten</h1>

In [ ]:
arr=np.array([[1,2],[3,4]])
print('c : ',arr.flatten(order='C'))
print('f : ',arr.flatten(order='F'))
print('a : ',arr.flatten(order='A'))
print('k : ',arr.flatten(order='K'))

c :  [1 2 3 4]
f :  [1 3 2 4]
a :  [1 2 3 4]
k :  [1 2 3 4]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print('c :', np.ravel(arr,order='C'))
print('f :',np.ravel(arr,order='F'))

c : [1 2 3 4 5 6]
f : [1 4 2 5 3 6]


<h1>16. Numpy 객체를 저장하고 로드하는 방법</h1>

In [ ]:
arr=np.array([1,2,3,4,5,6])
np.save('저장',arr)

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([1,2,3,4,5,6])
np.savez('저장2.npz',arr1,arr2)

In [ ]:
c_arr=np.array([1,2,3,4,5,6,7,8])
np.savetxt('저장3.csv',c_arr)

In [ ]:
l_arr=np.load('./저장.npy')
print(l_arr)
l_arr2=np.load('./저장2.npz')
print(l_arr2)

[1 2 3 4 5 6]


In [ ]:
arr_0=np.load('./저장2.npz')['arr_0']
print(arr_0)

[1 2 3]


In [ ]:
arr_t=np.loadtxt('저장3.csv')
print(arr_t)

[1. 2. 3. 4. 5. 6. 7. 8.]


<h1>17. Pandas란 </h1>
<h1>18. 시리즈와 데이터 프레임</h1>

In [ ]:
import pandas as pd

In [ ]:
s=pd.Series([1,3,5,6,8])
print(s)
print('---------------------')
s1=pd.Series([1,3,5,6,7],index=['하나','둘','셋','넷','다섯'])
print(s1)

0    1
1    3
2    5
3    6
4    8
dtype: int64
---------------------
하나    1
둘     3
셋     5
넷     6
다섯    7
dtype: int64


In [ ]:
#list -> Series데이터
list_data=[1,2,3,4,5]
series=pd.Series(list_data)
print(series)
print('\n')
list_index=['하나','둘','셋','넷','다섯']
new_series=pd.Series(list_data,index=list_index)
print(new_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


하나    1
둘     2
셋     3
넷     4
다섯    5
dtype: int64


In [ ]:
#tuple -> Series데이터
tuple_data=('판','다','스','꿀','잼')
series=pd.Series(tuple_data)
print(series)
print('|n')

tuple_index=('하나','둘','셋','넷','다섯')
new_series=pd.Series(tuple_data,index=tuple_index)
print(new_series)

0    판
1    다
2    스
3    꿀
4    잼
dtype: object
|n
하나    판
둘     다
셋     스
넷     꿀
다섯    잼
dtype: object


In [ ]:
dict_data={'a':1,'b':2,'c':3}
sr=pd.Series(dict_data)
print(dict_data)
print('\n')
print(type(sr))
print('\n')
print(sr)

{'a': 1, 'b': 2, 'c': 3}


<class 'pandas.core.series.Series'>


a    1
b    2
c    3
dtype: int64


In [ ]:
series_data=pd.Series(['홍길동','26','010-777-7777','광주','학생'],
                      index=['이름','나이','전화번호','거주지','직업'])
#정수형 위치 index로 가져오기
n_index=series_data[2]
print(n_index)
print('\n')
#index이름으로 가져오기
n_index=series_data['이름']
print(n_index)
print('\n')
print('전체 데이터 프레임 입니다.')
print(series_data)

010-777-7777


홍길동


전체 데이터 프레임 입니다.
이름               홍길동
나이                26
전화번호    010-777-7777
거주지               광주
직업                학생
dtype: object


In [ ]:
series_data=pd.Series(['홍길동','26','010-777-7777','광주','학생'],
                      index=['이름','나이','전화번호','거주지','직업'])
new=series_data[[0,1,3]]
print(new)
print('\n')
new=series_data[['이름','거주지','직업']]
print(new)

이름     홍길동
나이      26
거주지     광주
dtype: object


이름     홍길동
거주지     광주
직업      학생
dtype: object


In [ ]:
series_data=pd.Series(['홍길동','26','010-777-7777','광주','학생'],
                      index=['이름','나이','전화번호','거주지','직업'])
new=series_data[2:4]
print(new)
print('\n')
new=series_data['나이':'거주지']
print(new)

전화번호    010-777-7777
거주지               광주
dtype: object


나이                26
전화번호    010-777-7777
거주지               광주
dtype: object


In [ ]:
#Series 속성 관련 함수들
new_series=pd.Series(['welcome','to','pandas'],index=['here','is','Gwangju'])
print(new_series.index)
print(new_series.values)

Index(['here', 'is', 'Gwangju'], dtype='object')
['welcome' 'to' 'pandas']


<h2>Pandas-Data Frame</h2>
Data Frame을 만들 때는 2차원 데이터, index, column 3가지가 필요

In [ ]:
list_data_2d=[[23,'남','부산'],[21,'여','서울'],[25,'남','광주'],[27,'여','대전'],[24,'여','광주']]
df=pd.DataFrame(list_data_2d,columns=['나이','성별','지역'])
print(df)
print('\n')
df=pd.DataFrame(list_data_2d,index=['상우','지원','민기','정민','수림'],columns=['나이','성별','지역'])
print(df)

   나이 성별  지역
0  23  남  부산
1  21  여  서울
2  25  남  광주
3  27  여  대전
4  24  여  광주


    나이 성별  지역
상우  23  남  부산
지원  21  여  서울
민기  25  남  광주
정민  27  여  대전
수림  24  여  광주


In [ ]:
tuple_data_2d=((23,'남','부산'),(21,'여','서울'),(25,'남','광주'),(27,'여','대전'),(24,'여','광주'))
df=pd.DataFrame(tuple_data_2d,columns=['나이','성별','지역'])
print(df)
print('\n')
df=pd.DataFrame(tuple_data_2d,index=['상우','지원','민기','정민','수림'],columns=['나이','성별','지역'])
print(df)

   나이 성별  지역
0  23  남  부산
1  21  여  서울
2  25  남  광주
3  27  여  대전
4  24  여  광주


    나이 성별  지역
상우  23  남  부산
지원  21  여  서울
민기  25  남  광주
정민  27  여  대전
수림  24  여  광주


In [ ]:
dict_data={'나이':[23,21,25,27,24],'성별':['남','여','남','여','여'],'지역':['부산','서울','광주','대전','광주']}
df=pd.DataFrame(dict_data)
print(df)
print('\n')
df=pd.DataFrame(dict_data,index=['상우','지원','민기','정민','수림'])
print(df)

   나이 성별  지역
0  23  남  부산
1  21  여  서울
2  25  남  광주
3  27  여  대전
4  24  여  광주


    나이 성별  지역
상우  23  남  부산
지원  21  여  서울
민기  25  남  광주
정민  27  여  대전
수림  24  여  광주


19. 특정 데이터 선택하기

In [ ]:
#열선택
test_data={'팀이름':['아자아자','할수있다','AI마피아','TF고수','경사하강법','광인사'],
           '창의성':['상','중','하','상','중','하'],
           '완성도':[100,80,70,90,50,60],
           '사업성':['좋음','보통','부족','보통','잘함','못함']}
df=pd.DataFrame(test_data)
df

팀이름 창의성  완성도 사업성
0   아자아자   상  100  좋음
1   할수있다   중   80  보통
2  AI마피아   하   70  부족
3   TF고수   상   90  보통
4  경사하강법   중   50  잘함
5    광인사   하   60  못함

In [ ]:
print(df['팀이름'])
print(df['사업성'])
print('\n')
print(df.팀이름)
print(df.사업성)
df[['팀이름','사업성']]

0     아자아자
1     할수있다
2    AI마피아
3     TF고수
4    경사하강법
5      광인사
Name: 팀이름, dtype: object
0    좋음
1    보통
2    부족
3    보통
4    잘함
5    못함
Name: 사업성, dtype: object


0     아자아자
1     할수있다
2    AI마피아
3     TF고수
4    경사하강법
5      광인사
Name: 팀이름, dtype: object
0    좋음
1    보통
2    부족
3    보통
4    잘함
5    못함
Name: 사업성, dtype: object


팀이름 사업성
0   아자아자  좋음
1   할수있다  보통
2  AI마피아  부족
3   TF고수  보통
4  경사하강법  잘함
5    광인사  못함

In [ ]:
#행 선택
test_data={'팀이름':['아자아자','할수있다','AI마피아','TF고수','경사하강법','광인사'],
           '창의성':['상','중','하','상','중','하'],
           '완성도':[100,80,70,90,50,60],
           '사업성':['좋음','보통','부족','보통','잘함','못함']}
df=pd.DataFrame(test_data,index=['11팀','12팀','13팀','14팀','15팀','16팀'])
print(df.loc[['13팀']])
print(df.iloc[[1]])
print('=====================================')

df.loc[['11팀','14팀']]
print('\n')
df.iloc[[2,5]]

print('\n')
df.loc['12팀':'14팀']
df.iloc[1:5]

print('\n')
df.loc['12팀'::2]
df.iloc[1::2]

       팀이름 창의성  완성도 사업성
13팀  AI마피아   하   70  부족
      팀이름 창의성  완성도 사업성
12팀  할수있다   중   80  보통








팀이름 창의성  완성도 사업성
12팀  할수있다   중   80  보통
14팀  TF고수   상   90  보통
16팀   광인사   하   60  못함

In [ ]:
#원소 선택
test_data={'이름':['상우','현정','문영','동엽','우제'],
           '국어':[85,88,90,50,70],
           '수학':[57,90,100,78,66],
           '영어':[85,89,67,98,98],
           '과학':[93,79,92,50,70],
           '체육':[94,80,99,69,100]}
df=pd.DataFrame(test_data)
df.set_index('이름',inplace=True)    #'이름'을 index로 설정
df

국어   수학  영어  과학   체육
이름                      
상우  85   57  85  93   94
현정  88   90  89  79   80
문영  90  100  67  92   99
동엽  50   78  98  50   69
우제  70   66  98  70  100

In [ ]:
df.loc[['문영'],['영어']]

영어
이름    
문영  67

In [ ]:
df.iloc[[1],[1]]

수학
이름    
현정  90

In [ ]:
df.loc[['문영'],['국어','체육']]

국어  체육
이름        
문영  90  99

In [ ]:
df.iloc[[2],[0,3]]

국어  과학
이름        
문영  90  92

In [ ]:
df.loc[['문영','동엽'],['국어']]

국어
이름    
문영  90
동엽  50

In [ ]:
df.iloc[[1,3],[0,2,4]]

국어  영어  체육
이름            
현정  88  89  80
동엽  50  98  69

20.Index활용

In [ ]:
test_data={'이름':['상우','현정','문영','동엽','우제'],
           '국어':[85,88,90,50,70],
           '수학':[57,90,100,78,66],
           '영어':[85,89,67,98,98],
           '과학':[93,79,92,50,70],
           '체육':[94,80,99,69,100]}
df=pd.DataFrame(test_data)
df

이름  국어   수학  영어  과학   체육
0  상우  85   57  85  93   94
1  현정  88   90  89  79   80
2  문영  90  100  67  92   99
3  동엽  50   78  98  50   69
4  우제  70   66  98  70  100

In [ ]:
df['체육']=90
df['사회']=[89,69,79,80,100]
df

이름  국어   수학  영어  과학  체육   사회
0  상우  85   57  85  93  90   89
1  현정  88   90  89  79  90   69
2  문영  90  100  67  92  90   79
3  동엽  50   78  98  50  90   80
4  우제  70   66  98  70  90  100

In [ ]:
df.loc[5]=100
df.loc[6]=['jack',90,100,92,93,95,96]
df.loc['일곱']=['Michael',71,72,75,76,74,73]
df

이름   국어   수학   영어   과학   체육   사회
0        상우   85   57   85   93   90   89
1        현정   88   90   89   79   90   69
2        문영   90  100   67   92   90   79
3        동엽   50   78   98   50   90   80
4        우제   70   66   98   70   90  100
5       100  100  100  100  100  100  100
6      jack   90  100   92   93   95   96
일곱  Michael   71   72   75   76   74   73

In [ ]:
test_data={'상호명':['상우네','현정이네','문영이네','동엽이네','우제네'],
           '사과':[850,880,900,500,700],
           '배':[570,900,1000,780,660],
           '딸기':[850,890,670,980,908],
           '포도':[930,790,920,500,700]}
df=pd.DataFrame(test_data)
print(df)

new_df1=df.set_index('상호명')
print(new_df1)

new_df2=df.set_index(['사과'])
print(new_df2)

df.set_index(['상호명'],inplace=True)
df

    상호명   사과     배   딸기   포도
0   상우네  850   570  850  930
1  현정이네  880   900  890  790
2  문영이네  900  1000  670  920
3  동엽이네  500   780  980  500
4   우제네  700   660  908  700
       사과     배   딸기   포도
상호명                      
상우네   850   570  850  930
현정이네  880   900  890  790
문영이네  900  1000  670  920
동엽이네  500   780  980  500
우제네   700   660  908  700
      상호명     배   딸기   포도
사과                       
850   상우네   570  850  930
880  현정이네   900  890  790
900  문영이네  1000  670  920
500  동엽이네   780  980  500
700   우제네   660  908  700


사과     배   딸기   포도
상호명                      
상우네   850   570  850  930
현정이네  880   900  890  790
문영이네  900  1000  670  920
동엽이네  500   780  980  500
우제네   700   660  908  700

In [ ]:
df1=pd.DataFrame(test_data,index=[4,2,1,0,3])
print(df1)
print('\n')

new_index=[0,1,2,3,4,5]
reindex_df1=df1.reindex(new_index)
print(reindex_df1)

#fill_value로 NaN 데이터 채우기
reindex_df2=df1.reindex(new_index,fill_value=777)
reindex_df2

    상호명   사과     배   딸기   포도
4   상우네  850   570  850  930
2  현정이네  880   900  890  790
1  문영이네  900  1000  670  920
0  동엽이네  500   780  980  500
3   우제네  700   660  908  700


    상호명     사과       배     딸기     포도
0  동엽이네  500.0   780.0  980.0  500.0
1  문영이네  900.0  1000.0  670.0  920.0
2  현정이네  880.0   900.0  890.0  790.0
3   우제네  700.0   660.0  908.0  700.0
4   상우네  850.0   570.0  850.0  930.0
5   NaN    NaN     NaN    NaN    NaN


상호명   사과     배   딸기   포도
0  동엽이네  500   780  980  500
1  문영이네  900  1000  670  920
2  현정이네  880   900  890  790
3   우제네  700   660  908  700
4   상우네  850   570  850  930
5   777  777   777  777  777

In [ ]:
reindex_df2.set_index('상호명',inplace=True)
reindex_df2.reset_index()

상호명   사과     배   딸기   포도
0  동엽이네  500   780  980  500
1  문영이네  900  1000  670  920
2  현정이네  880   900  890  790
3   우제네  700   660  908  700
4   상우네  850   570  850  930
5   777  777   777  777  777

In [ ]:
test_data={'상호명':['상우네','현정이네','문영이네','동엽이네','우제네'],
           '사과':[850,880,900,500,700],
           '배':[570,900,1000,780,660],
           '딸기':[850,890,670,980,908],
           '포도':[930,790,920,500,700]}
df=pd.DataFrame(test_data,index=[4,2,1,0,3])
print(df)
print('\n')
sorted_df=df.sort_index()
print(sorted_df)
print('\n')

#오름차순 True, 내림차순 False
ascending_df=df.sort_index(ascending=True)
print(ascending_df)
descending_df=df.sort_index(ascending=False)
descending_df

    상호명   사과     배   딸기   포도
4   상우네  850   570  850  930
2  현정이네  880   900  890  790
1  문영이네  900  1000  670  920
0  동엽이네  500   780  980  500
3   우제네  700   660  908  700


    상호명   사과     배   딸기   포도
0  동엽이네  500   780  980  500
1  문영이네  900  1000  670  920
2  현정이네  880   900  890  790
3   우제네  700   660  908  700
4   상우네  850   570  850  930


    상호명   사과     배   딸기   포도
0  동엽이네  500   780  980  500
1  문영이네  900  1000  670  920
2  현정이네  880   900  890  790
3   우제네  700   660  908  700
4   상우네  850   570  850  930


상호명   사과     배   딸기   포도
4   상우네  850   570  850  930
3   우제네  700   660  908  700
2  현정이네  880   900  890  790
1  문영이네  900  1000  670  920
0  동엽이네  500   780  980  500

In [ ]:
#행,열 삭제
test_data={'상호명':['상우네','현정이네','문영이네','동엽이네','우제네'],
           '사과':[850,880,900,500,700],
           '배':[570,900,1000,780,660],
           '딸기':[850,890,670,980,908],
           '포도':[930,790,920,500,700]}
df=pd.DataFrame(test_data)
df.set_index('상호명',inplace=True)
print(df)

ndf1=df.drop('사과',axis=1)
print(ndf1)

ndf2=df.drop(['사과','딸기'],axis=1)
print(ndf2)

ndf3=df.drop('상우네')
print(ndf3)

ndf4=df.drop(['현정이네','문영이네'])
ndf4

       사과     배   딸기   포도
상호명                      
상우네   850   570  850  930
현정이네  880   900  890  790
문영이네  900  1000  670  920
동엽이네  500   780  980  500
우제네   700   660  908  700
         배   딸기   포도
상호명                 
상우네    570  850  930
현정이네   900  890  790
문영이네  1000  670  920
동엽이네   780  980  500
우제네    660  908  700
         배   포도
상호명            
상우네    570  930
현정이네   900  790
문영이네  1000  920
동엽이네   780  500
우제네    660  700
       사과     배   딸기   포도
상호명                      
현정이네  880   900  890  790
문영이네  900  1000  670  920
동엽이네  500   780  980  500
우제네   700   660  908  700


사과    배   딸기   포도
상호명                     
상우네   850  570  850  930
동엽이네  500  780  980  500
우제네   700  660  908  700

21. Pandas Data 입출력

In [ ]:
data={'이름':['상우','민철','민지'],
      '미적':['A+','B+','C'],
      '물리학':['C+','A+','A'],
      'Python':['A+','B+','A+']}
df=pd.DataFrame(data)
df.set_index('이름',inplace=True)
df.to_csv('./df_tocsv.csv')
df

미적 물리학 Python
이름               
상우  A+  C+     A+
민철  B+  A+     B+
민지   C   A     A+

In [ ]:
data={"이름":{"1번":"상우","2번":"민성","3번":"지현"},
 "나이":{"1번":26,"2번":22,"3번":24},
 "취미":{"1번":"서핑","2번":"독서","3번":"자전거"},
 "거주지":{"1번":"부산","2번":"대전","3번":"광주"}}
df=pd.DataFrame(data)
df.to_json('./tojson.json')

In [ ]:
df=pd.read_json('tojson.json')
print(df)
df.set_index('이름',inplace=True)
df

    이름  나이   취미 거주지
1번  상우  26   서핑  부산
2번  민성  22   독서  대전
3번  지현  24  자전거  광주


나이   취미 거주지
이름             
상우  26   서핑  부산
민성  22   독서  대전
지현  24  자전거  광주

22.Pandas 연산

In [ ]:
dict_data={'c0':[1,2,3],'c1':[4,5,6],
           'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,15]}
df=pd.DataFrame(dict_data)
add = df + 10
print(add)
print('\n')
sub=df-10
print(sub)
print('\n')
mul=df*10
print(mul)
print('\n')
div=df/10
print(div)

   c0  c1  c2  c3  c4
0  11  14  17  20  23
1  12  15  18  21  24
2  13  16  19  22  25


   c0  c1  c2  c3  c4
0  -9  -6  -3   0   3
1  -8  -5  -2   1   4
2  -7  -4  -1   2   5


   c0  c1  c2   c3   c4
0  10  40  70  100  130
1  20  50  80  110  140
2  30  60  90  120  150


    c0   c1   c2   c3   c4
0  0.1  0.4  0.7  1.0  1.3
1  0.2  0.5  0.8  1.1  1.4
2  0.3  0.6  0.9  1.2  1.5


In [ ]:
data_1={'c0':[1,2,3],'c1':[4,5,6],
           'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,15]}
data_2={'c0':[1,2,3],'c1':[4,5,6],
           'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,np.nan]}
df_1=pd.DataFrame(data_1)
df_2=pd.DataFrame(data_2)
df_1+df_2

c0  c1  c2  c3    c4
0   2   8  14  20  26.0
1   4  10  16  22  28.0
2   6  12  18  24   NaN

23. Pandas 간단한 통계 메소드

In [ ]:
import random
data_1=[]
data_2=[]
for i in range(0,10):
  data_1.append(random.uniform(0,1))     #uniform : 0부터 1사이의 수를 랜덤하게 꺼냄
for i in range(0,10):
  data_2.append(random.uniform(0,2))
dict_data={'first':data_1,'second':data_2 }
index_data=['zero','1st','2nd','3rd','4th','5th','6th','7th','8th','9th']
df=pd.DataFrame(dict_data, index=index_data)
print(df)
print('\n')

#평균
mean_val=df.mean()
first_mean=df['first'].mean()
print('first 평균 : ',first_mean)
second_mean=df['second'].mean()
print('second 평균 :',second_mean)
print('\n')
print('--------------')
#중간값
median_val=df.median()
first_median=df['first'].median()
second_median=df['second'].median()
print(median_val)
print('\n')
print('first 중간값 : ',first_median)
print('second 중간값 : ',second_median)

         first    second
zero  0.798446  1.632417
1st   0.984865  1.764004
2nd   0.339982  0.411599
3rd   0.318018  0.157759
4th   0.464940  1.534509
5th   0.205503  0.574292
6th   0.733110  0.204669
7th   0.555191  0.744592
8th   0.655919  1.053026
9th   0.645076  1.149963


first 평균 :  0.5701048970632455
second 평균 : 0.9226829962773259


--------------
first     0.600134
second    0.898809
dtype: float64


first 중간값 :  0.600133665146614
second 중간값 :  0.8988094265428247


In [ ]:
#최댓값
max_val=df.max()
print(max_val)
print('\n')
first_max=df['first'].max()
print(first_max)
second_max=df['second'].max()
print(second_max)

print('================')
#최솟값
min_val=df.min()
first_min=df['first'].min()
second_min=df['second'].min()
print(min_val)
print('\n')
print('first 최솟값',first_min)
print('second 최솟값',second_min)

In [ ]:
#표준편차
std_val=df.std()
first_std=df['first'].std()
second_std=df['second'].std()
print(std_val)
print('\n')
print(f'first 표준편차 : {first_std}')
print(f'second 표준편차 : {second_std}')

In [ ]:
#상관계수
data_3=[]
for i in range(0,10):
  data_3.append(random.uniform(0,2))
dict_data={'first':data_1,
           'second':data_2,
           'third':data_3}
index_data=['zero','1st','2nd','3rd','4th','5th','6th','7th','8th','9th']
ndf=pd.DataFrame(dict_data,index=index_data)
print(ndf)
print('=====================================')
corr_val=ndf.corr()
print(corr_val)
print('\n')
first_third_corr=ndf[['first','third']].corr()
first_third_corr

24.pandas 활용 기초

In [ ]:
#누락데이터 NaN(Not a Number)
import seaborn as sns
df=sns.load_dataset('titanic')
print(df.tail())
print('\n')

#info(), value_counts()
print(df.info())
print('\n')
print('-----------------------=--============================---------')
nan_df=df['deck'].value_counts(dropna=False)
print(nan_df)

print('=============================================================')
#isnull(),notnull()
print(df.head().isnull())    #원소가 NaN데이터일 경우 True 반환,유효 데이터일 경우 False
df.head().notnull()   #Nan데이터일 경우 False 반환

In [ ]:
#dropna(), thresh 옵션 : 누락 데이터가 전체 데이터 개수의 절반을 넘는 열을 제거
print(df.isnull().sum(axis=0))
print('\n')
ndf=df.dropna(axis=1,thresh=445)
print(ndf.columns)
print('---------------------------')
#dropna(), how옵션 : NaN데이터가 존재하는 모든 행 제거
ndf2=ndf.dropna(subset=['age'],how='any',axis=0) 
print(ndf2.isnull().sum(axis=0))
print('\n')
print(ndf2.notnull().sum(axis=0))

In [ ]:
#누락 데이터 채우기
df.dropna(axis=1,thresh=445,inplace=True)
age_median=df['age'].median(axis=0)
df['age'].fillna(age_median,inplace=True)
df.isnull().sum(axis=0)

In [ ]:
#중복데이터 확인,제거
data={'c0':['a','a','c','d','e','f','c'],
      'c1':[1,1,2,3,4,5,2],
      'c2':[1,1,2,3,4,5,2],
      'c3':['a','a','c','d','e','f','c']}
df=pd.DataFrame(data)
duplicated_df=df.duplicated()   #duplicated()는 이전의 행과 비교하여 중복되는 행일 경우 True, 처음 나오는 행은 False
print(duplicated_df)
df.drop_duplicates(inplace=True)
df

In [ ]:
#시계열 데이터
import pandas as pd
corona_df=pd.read_csv('PatientRoute.csv')
corona_df.head()

In [ ]:
#to_datetime() : 데이터를 Timestamp객체로 바꿔서 
corona_df['new_date']=pd.to_datetime(corona_df['date'])
print(corona_df.info())
corona_df.head()

In [ ]:
#to_period() : Timestamp객체를 일정 기간을 나타내는 Period 객체로 바꿀 수 있음, freq옵션을 사용하여 반복되는 기간 설정
#freq='D'1일, freq='M'1달, freq='A'1년
data=corona_df['new_date'].dt
freq_d=data.to_period(freq='D')
freq_m=data.to_period(freq='M')
freq_a=data.to_period(freq='A')
print(freq_d)
print('--------=-=-=--=-')
print(freq_m)
print(']========================[')
print(freq_a)

In [ ]:
#날짜 데이터 분리
#dt.day, dt.month, dt.year
corona_df['Year']=corona_df['new_date'].dt.year
corona_df['Month']=corona_df['new_date'].dt.month
corona_df['Day']=corona_df['new_date'].dt.day
corona_df.head()

In [ ]:
#날짜 인덱스 활용
corona_df=pd.read_csv('PatientRoute.csv')
corona_df['new_date']=pd.to_datetime(corona_df['date'])
corona_df.set_index('new_date',inplace=True)
corona_df

In [ ]:
#데이터 추출
corona_df_ym=corona_df.loc['2020-02']
print(corona_df_ym)
print('\n')
corona_df_ym_cols=corona_df.loc['2020-02','city':'longitude']
print(corona_df_ym_cols)
print('\n')
corona_df_ymd_range=corona_df.loc['2020-02-22':'2020-02-23']
print(corona_df_ymd_range)

<head><h1>#html에서 데이터추출하기</h1></head>

In [ ]:
import pandas as pd
with open('html_source.txt','r')as f:
  tt=f.read()
  t1=tt.split('<div class="inner_number">')
  t1.pop(0)
tip=[]
for i in t1:
  tip.append(i.split('</div>')[0])
print(tip)

['223778', '223773', '223772', '223769', '223767', '223760', '223757', '223755', '223753', '223751', '223743', '223738', '223736', '223728', '223715']


In [ ]:
with open ('html_source.txt','r') as f:
  tt2=f.read()
  t2=tt2.split('<a class="article')
  t2.pop(0)
title=[]
for i in t2:
  i2=i.split('</a>')[0]
  title.append(i2.split('>')[-1])
#i2.split().split()

title2=[]
for k in title:
  t3=k.replace('\n','')
  t4=t3.replace(' ','')
  title2.append(t4)
print(title2)

['YuhkiKuramoto-Meditation', 'CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)', 'Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)', 'IraisemyhandshightotheLord(내손을주께높이듭니다)', '아이유가을아침기타커버!', 'GIN-Recollection(cover)', 'EdGerhard-TheWaterisWide/Cover', '비틀즈의IWill연주해보았습니다.', 'TommyEmmanuel-Closetoyou커버', 'BTS(방탄소년단)-Butter쳐봤습니다!!', '[뽕용Live]KotaroOshio-Twilight(Livestage/coverby기타치는뽕용)', 'Creep편곡', '양희은아이유-가을아침기타커버입니다!', '쾌지나칭칭나네편곡', 'DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)']


In [ ]:
pd_arr=pd.DataFrame(title2,index=tip,columns=['<노래제목>'])
print(pd_arr)

                                                   <노래제목>
223778                           YuhkiKuramoto-Meditation
223773          CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)
223772    Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)
223769             IraisemyhandshightotheLord(내손을주께높이듭니다)
223767                                       아이유가을아침기타커버!
223760                            GIN-Recollection(cover)
223757                     EdGerhard-TheWaterisWide/Cover
223755                                 비틀즈의IWill연주해보았습니다.
223753                         TommyEmmanuel-Closetoyou커버
223751                           BTS(방탄소년단)-Butter쳐봤습니다!!
223743  [뽕용Live]KotaroOshio-Twilight(Livestage/coverby...
223738                                            Creep편곡
223736                                양희은아이유-가을아침기타커버입니다!
223728                                          쾌지나칭칭나네편곡
223715  DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)


In [ ]:
pd_arr=pd_arr.reset_index()
print(pd_arr)

     index                                             <노래제목>
0   223778                           YuhkiKuramoto-Meditation
1   223773          CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)
2   223772    Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)
3   223769             IraisemyhandshightotheLord(내손을주께높이듭니다)
4   223767                                       아이유가을아침기타커버!
5   223760                            GIN-Recollection(cover)
6   223757                     EdGerhard-TheWaterisWide/Cover
7   223755                                 비틀즈의IWill연주해보았습니다.
8   223753                         TommyEmmanuel-Closetoyou커버
9   223751                           BTS(방탄소년단)-Butter쳐봤습니다!!
10  223743  [뽕용Live]KotaroOshio-Twilight(Livestage/coverby...
11  223738                                            Creep편곡
12  223736                                양희은아이유-가을아침기타커버입니다!
13  223728                                          쾌지나칭칭나네편곡
14  223715  DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)


In [ ]:
pd_arr.columns=['<글번호>','<노래제목>']
print(pd_arr)

     <글번호>                                             <노래제목>
0   223778                           YuhkiKuramoto-Meditation
1   223773          CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)
2   223772    Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)
3   223769             IraisemyhandshightotheLord(내손을주께높이듭니다)
4   223767                                       아이유가을아침기타커버!
5   223760                            GIN-Recollection(cover)
6   223757                     EdGerhard-TheWaterisWide/Cover
7   223755                                 비틀즈의IWill연주해보았습니다.
8   223753                         TommyEmmanuel-Closetoyou커버
9   223751                           BTS(방탄소년단)-Butter쳐봤습니다!!
10  223743  [뽕용Live]KotaroOshio-Twilight(Livestage/coverby...
11  223738                                            Creep편곡
12  223736                                양희은아이유-가을아침기타커버입니다!
13  223728                                          쾌지나칭칭나네편곡
14  223715  DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)


In [ ]:
with open ('html_source.txt','r') as f:
  tt3=f.read()
  t3=tt3.split('<td class="td_date">')
  t3.pop(0)
date=[]
for i in t3:
  date.append(i.split('</td>')[0])
date_1=date.pop(0)
print(date)

['2021.06.19.', '2021.06.19.', '2021.06.19.', '2021.06.19.', '2021.06.19.', '2021.06.18.', '2021.06.18.', '2021.06.18.', '2021.06.18.', '2021.06.18.', '2021.06.17.', '2021.06.16.', '2021.06.16.', '2021.06.15.', '2021.06.14.']


In [ ]:
pd_arr['날짜']=date
pd_arr

<글번호>                                             <노래제목>           날짜
0   223778                           YuhkiKuramoto-Meditation  2021.06.19.
1   223773          CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)  2021.06.19.
2   223772    Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)  2021.06.19.
3   223769             IraisemyhandshightotheLord(내손을주께높이듭니다)  2021.06.19.
4   223767                                       아이유가을아침기타커버!  2021.06.19.
5   223760                            GIN-Recollection(cover)  2021.06.18.
6   223757                     EdGerhard-TheWaterisWide/Cover  2021.06.18.
7   223755                                 비틀즈의IWill연주해보았습니다.  2021.06.18.
8   223753                         TommyEmmanuel-Closetoyou커버  2021.06.18.
9   223751                           BTS(방탄소년단)-Butter쳐봤습니다!!  2021.06.18.
10  223743  [뽕용Live]KotaroOshio-Twilight(Livestage/coverby...  2021.06.17.
11  223738                                            Creep편곡  2021.06.16.
12  223736                                양희은아이유-가을아침기타커버입니다!  2021.06.16.
13  223728                                          쾌지나칭칭나네편곡  2021.06.15.
14  223715  DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)  2021.06.14.

In [ ]:
print(date_1)

2020.11.13.


In [ ]:
with open ('html_source.txt','r') as f:
  tt3=f.read()
  t3=tt3.split('필독</span>')
  t3.pop(0)
pg=[]
for i in t3:
  pg.append(i.split('</a>')[0].split('>')[-1])
pg2=[]
for i in pg:
  pg2.append(i.replace('\n','').replace('\t','').replace('  ',''))
print(pg2)

['KBS &lt;올댓뮤직&gt; 기타의 밤 특집 - 자이로, 장재훈, 김영소 등 출연분']


In [ ]:
pd_arr_g=pd.DataFrame([('공지',pg2,date_1)],columns=pd_arr.columns)
print(pd_arr_g)

  <글번호>                                             <노래제목>           날짜
0    공지  [KBS &lt;올댓뮤직&gt; 기타의 밤 특집 - 자이로, 장재훈, 김영소 등 출연분]  2020.11.13.


In [ ]:
pd_arr2=pd_arr_g.append(pd_arr)
pd_arr2

<글번호>                                             <노래제목>           날짜
0       공지  [KBS &lt;올댓뮤직&gt; 기타의 밤 특집 - 자이로, 장재훈, 김영소 등 출연분]  2020.11.13.
0   223778                           YuhkiKuramoto-Meditation  2021.06.19.
1   223773          CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)  2021.06.19.
2   223772    Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)  2021.06.19.
3   223769             IraisemyhandshightotheLord(내손을주께높이듭니다)  2021.06.19.
4   223767                                       아이유가을아침기타커버!  2021.06.19.
5   223760                            GIN-Recollection(cover)  2021.06.18.
6   223757                     EdGerhard-TheWaterisWide/Cover  2021.06.18.
7   223755                                 비틀즈의IWill연주해보았습니다.  2021.06.18.
8   223753                         TommyEmmanuel-Closetoyou커버  2021.06.18.
9   223751                           BTS(방탄소년단)-Butter쳐봤습니다!!  2021.06.18.
10  223743  [뽕용Live]KotaroOshio-Twilight(Livestage/coverby...  2021.06.17.
11  223738                                            Creep편곡  2021.06.16.
12  223736                                양희은아이유-가을아침기타커버입니다!  2021.06.16.
13  223728                                          쾌지나칭칭나네편곡  2021.06.15.
14  223715  DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)  2021.06.14.

In [ ]:
with open ('html_source.txt','r') as f:
  tt4=f.read()
  t4=tt4.split('<td class="td_name">')
  t4.pop(0)
wr=[]
for i in t4:
  wr.append(i.split('</td>')[0].split('</a')[0].split('>')[-1])
print(wr)

['진환', 'haryunban', '슈렉68', '슈렉68', '현하ll노동환', '찬튜', 'RECHEV', '성열형', '제이그루브', '뚱치땅치', '노력감', '기타치는뽕용', '이스코', '찬튜', 'QNP', '조각나암']


In [ ]:
pd_arr2['글쓴이']=wr
pd_arr2

<글번호>  ...        글쓴이
0       공지  ...         진환
0   223778  ...  haryunban
1   223773  ...       슈렉68
2   223772  ...       슈렉68
3   223769  ...    현하ll노동환
4   223767  ...         찬튜
5   223760  ...     RECHEV
6   223757  ...        성열형
7   223755  ...      제이그루브
8   223753  ...       뚱치땅치
9   223751  ...        노력감
10  223743  ...     기타치는뽕용
11  223738  ...        이스코
12  223736  ...         찬튜
13  223728  ...        QNP
14  223715  ...       조각나암

[16 rows x 4 columns]

In [ ]:
pd_arr2.set_index('<글번호>',inplace=True)
pd_arr2

<노래제목>  ...        글쓴이
<글번호>                                                      ...           
공지      [KBS &lt;올댓뮤직&gt; 기타의 밤 특집 - 자이로, 장재훈, 김영소 등 출연분]  ...         진환
223778                           YuhkiKuramoto-Meditation  ...  haryunban
223773          CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)  ...       슈렉68
223772    Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)  ...       슈렉68
223769             IraisemyhandshightotheLord(내손을주께높이듭니다)  ...    현하ll노동환
223767                                       아이유가을아침기타커버!  ...         찬튜
223760                            GIN-Recollection(cover)  ...     RECHEV
223757                     EdGerhard-TheWaterisWide/Cover  ...        성열형
223755                                 비틀즈의IWill연주해보았습니다.  ...      제이그루브
223753                         TommyEmmanuel-Closetoyou커버  ...       뚱치땅치
223751                           BTS(방탄소년단)-Butter쳐봤습니다!!  ...        노력감
223743  [뽕용Live]KotaroOshio-Twilight(Livestage/coverby...  ...     기타치는뽕용
223738                                            Creep편곡  ...        이스코
223736                                양희은아이유-가을아침기타커버입니다!  ...         찬튜
223728                                          쾌지나칭칭나네편곡  ...        QNP
223715  DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)  ...       조각나암

[16 rows x 3 columns]

In [ ]:
with open ('html_source.txt','r') as f:
  tt5=f.read()
  t5=tt5.split('<td class="td_view">')
  t5.pop(0)
vi=[]
for i in t5:
  vi.append(i.split('</td>')[0])
print(vi)

['1,860', '34', '15', '17', '11', '39', '21', '28', '19', '41', '86', '68', '86', '71', '43', '121']


In [ ]:
pd_arr2['조회수']=vi
pd_arr2

<노래제목>  ...    조회수
<글번호>                                                      ...       
공지      [KBS &lt;올댓뮤직&gt; 기타의 밤 특집 - 자이로, 장재훈, 김영소 등 출연분]  ...  1,860
223778                           YuhkiKuramoto-Meditation  ...     34
223773          CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)  ...     15
223772    Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)  ...     17
223769             IraisemyhandshightotheLord(내손을주께높이듭니다)  ...     11
223767                                       아이유가을아침기타커버!  ...     39
223760                            GIN-Recollection(cover)  ...     21
223757                     EdGerhard-TheWaterisWide/Cover  ...     28
223755                                 비틀즈의IWill연주해보았습니다.  ...     19
223753                         TommyEmmanuel-Closetoyou커버  ...     41
223751                           BTS(방탄소년단)-Butter쳐봤습니다!!  ...     86
223743  [뽕용Live]KotaroOshio-Twilight(Livestage/coverby...  ...     68
223738                                            Creep편곡  ...     86
223736                                양희은아이유-가을아침기타커버입니다!  ...     71
223728                                          쾌지나칭칭나네편곡  ...     43
223715  DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)  ...    121

[16 rows x 4 columns]

In [ ]:
with open ('html_source.txt','r') as f:
  tt6=f.read()
  t6=tt6.split('<td class="td_likes">')
  t6.pop(0)
li=[]
for i in t6:
  li.append(i.split('</td>')[0])
print(li)

['19', '1', '2', '0', '0', '0', '0', '1', '0', '1', '3', '0', '3', '0', '1', '3']


In [ ]:
pd_arr2['좋아요']=li
pd_arr2

<노래제목>  ... 좋아요
<글번호>                                                      ...    
공지      [KBS &lt;올댓뮤직&gt; 기타의 밤 특집 - 자이로, 장재훈, 김영소 등 출연분]  ...  19
223778                           YuhkiKuramoto-Meditation  ...   1
223773          CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)  ...   2
223772    Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)  ...   0
223769             IraisemyhandshightotheLord(내손을주께높이듭니다)  ...   0
223767                                       아이유가을아침기타커버!  ...   0
223760                            GIN-Recollection(cover)  ...   0
223757                     EdGerhard-TheWaterisWide/Cover  ...   1
223755                                 비틀즈의IWill연주해보았습니다.  ...   0
223753                         TommyEmmanuel-Closetoyou커버  ...   1
223751                           BTS(방탄소년단)-Butter쳐봤습니다!!  ...   3
223743  [뽕용Live]KotaroOshio-Twilight(Livestage/coverby...  ...   0
223738                                            Creep편곡  ...   3
223736                                양희은아이유-가을아침기타커버입니다!  ...   0
223728                                          쾌지나칭칭나네편곡  ...   1
223715  DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)  ...   3

[16 rows x 5 columns]

In [ ]:
#from, import
from B import Blogg
blg=Blogg('html_source.txt')
blg.generate_dataframe()

In [ ]:
#카페 정보 크롤러

import pandas as pd
class Blogg:
  def __init__(self,path):
    f=open(path,'r',encoding='UTF-8')
    self.source=f.read()
    self.df=pd.DataFrame()
  def generate_dataframe(self):
    self.sn()
    self.st()
    self.sg()
    self.swr()
    self.sd()
    self.sv()
    self.sl()
    self.df.set_index('글번호',inplace=True)
    return self.df
  
  def sn(self):
    tn=self.source.split('<div class="inner_number">')
    tn.pop(0)
    number_list=[]
    for i in tn:
      number_list.append(i.split('</div>')[0])
    self.df['글번호']=number_list
  
  def st(self):
    tt=self.source.split('<a class="article')
    tt.pop(0)
    title_list=[]
    for i in tt:
      title_list.append(i.split('</a>')[0].split('>')[-1])
    title_list2=[]
    for j in title_list:
      j1=j.replace('\n','')
      j2=j1.replace(' ','')
      title_list2.append(j2)
    self.df['제목']=title_list2
  
  def sg(self):
    if '필독' in self.source:
      tg=self.source.split('필독</span>')
      tg.pop(0)
      title_g=[]
      for i in tg:
        title_g.append(i.split('</a>')[0].split('>')[-1])
      title_g2=[]
      for j in title_g:
        title_g2.append(j.replace('\n','').replace('\t','').replace('  ',''))
      df_g=pd.DataFrame([('공지',title_g2)],columns=self.df.columns)
      self.df=df_g.append(self.df)
    else:
      pass


  def swr(self):
    twr=self.source.split('<td class="td_name">')
    twr.pop(0)
    title_writer=[]
    for i in twr:
      title_writer.append(i.split('</td>')[0].split('</a')[0].split('>')[-1])
    self.df['글쓴이']=title_writer

  def sd(self):
    sd=self.source.split('<td class="td_date">')
    sd.pop(0)
    title_date=[]
    for i in sd:
      title_date.append(i.split('</td>')[0])
    self.df['날짜']=title_date

  def sv(self):
    sv=self.source.split('<td class="td_view">')
    sv.pop(0)
    title_view=[]
    for i in sv:
      i2=i.split('</td>')[0]
      i3=i2.replace(',','')
      title_view.append(int(i3))

    self.df['조회수']=title_view

  def sl(self):
    sl=self.source.split('<td class="td_likes">')
    sl.pop(0)
    title_like=[]
    for i in sl:
      title_like.append(i.split('</td>')[0])
    self.df['좋아요']=title_like


  def filter_view(self,low,**kwargs):
    if not kwargs.get('high'):
      return self.df[self.df['조회수']>=low]
    else:
      return self.df[(self.df['조회수']<kwargs['high'])&(self.df['조회수']>=low)]

  def filter_date(self,low,**kwargs):
    if not kwargs.get('high'):
      return self.df[self.df['날짜']>=low]
    else:
      return self.df[(self.df['날짜']<kwargs['high'])&(self.df['날짜']>=low)]

  def export_csv(self):
    self.df.to_csv('./wow.csv')
  def import_csv(self,path):
    self.df=pd.read_csv(path)

In [ ]:
blg=Blogg('html_source.txt')
blg.generate_dataframe()

제목        글쓴이  ...   조회수  좋아요
글번호                                                                   ...           
공지      [KBS &lt;올댓뮤직&gt; 기타의 밤 특집 - 자이로, 장재훈, 김영소 등 출연분]         진환  ...  1860   19
223778                           YuhkiKuramoto-Meditation  haryunban  ...    34    1
223773          CCMfinger-style-참좋으신주님(김기영작곡,arr.byShrek)       슈렉68  ...    15    2
223772    Guitarsolo-JustFallInLoveAgain(AnneMurray,1978)       슈렉68  ...    17    0
223769             IraisemyhandshightotheLord(내손을주께높이듭니다)    현하ll노동환  ...    11    0
223767                                       아이유가을아침기타커버!         찬튜  ...    39    0
223760                            GIN-Recollection(cover)     RECHEV  ...    21    0
223757                     EdGerhard-TheWaterisWide/Cover        성열형  ...    28    1
223755                                 비틀즈의IWill연주해보았습니다.      제이그루브  ...    19    0
223753                         TommyEmmanuel-Closetoyou커버       뚱치땅치  ...    41    1
223751                           BTS(방탄소년단)-Butter쳐봤습니다!!        노력감  ...    86    3
223743  [뽕용Live]KotaroOshio-Twilight(Livestage/coverby...     기타치는뽕용  ...    68    0
223738                                            Creep편곡        이스코  ...    86    3
223736                                양희은아이유-가을아침기타커버입니다!         찬튜  ...    71    0
223728                                          쾌지나칭칭나네편곡        QNP  ...    43    1
223715  DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)       조각나암  ...   121    3

[16 rows x 5 columns]

In [ ]:
blg.filter_view(30, high=40)

제목        글쓴이           날짜  조회수 좋아요
글번호                                                              
223778  YuhkiKuramoto-Meditation  haryunban  2021.06.19.   34   1
223767              아이유가을아침기타커버!         찬튜  2021.06.19.   39   0

In [ ]:
blg.filter_date('2021.06.14',high='2021.06.17')

제목   글쓴이  ...  조회수  좋아요
글번호                                                              ...          
223738                                            Creep편곡   이스코  ...   86    3
223736                                양희은아이유-가을아침기타커버입니다!    찬튜  ...   71    0
223728                                          쾌지나칭칭나네편곡   QNP  ...   43    1
223715  DEPAPEPE(데파페페,デパペペ)-두사람의사진(Photographoftwopeople)  조각나암  ...  121    3

[4 rows x 5 columns]

In [ ]:
P=('page1.txt','page2.txt','page3.txt','page4.txt','page5.txt','page6.txt','page7.txt','page8.txt','page9.txt')
for i in P:
  p1=Blogg(i)
  print(p1.generate_dataframe())

                                                       제목       글쓴이  ...   조회수  좋아요
글번호                                                                  ...           
공지      [KBS &lt;올댓뮤직&gt; 기타의 밤 특집 - 자이로, 장재훈, 김영소 등 출연분]        진환  ...  1875   19
223826                             열정적인곡이죠'라쿰파르시타'기타연주입니다        찬튜  ...    26    0
223824                                      바다와갈매기소리와함께연주    오스카피터슨  ...     8    0
223823                              하나님의나팔소리CCM연주(피아노,기타)    오스카피터슨  ...     3    0
223822                            옳은길따르라의의길을CCM연주(피아노,기타)    오스카피터슨  ...     4    0
223821                                         캐논변주곡기타연주!        찬튜  ...    26    0
223819                              (경서)밤하늘의별을-SunghaJung       책갈피  ...    45    2
223818                          Déjàvu-AntoineDufour(데자뷰)      오리무중  ...    46    5
223816                            슬기로운의사생활2ost-이무진-비와당신커버   hbj0128  ...    46    2
223815                                     fight피드백부탁드립니다  기타치는 맹꽁이  ...    